project:
  type: website

website:
  title: "Chemical and Thermal Processes"
  navbar:
    logo: DOFPro_D7_Red_Flame_No_Background_cropped.png
    logo-alt: "DOFPro Logo"
    logo-href: https://dofpro.org
    search: true
    left:
      - href: basics/
      - text: 'Basics'
        menu:
        - href: basics/index.qmd
          text: Basics
        - href: basics/WhatIsAMole.qmd
          text: 'What Is a Mole?'
        - href: basics/WhatIsAMoleJTF.qmd
          text: 'What Is a Mole? JTF'
      - text: 'Balances'
        menu:
        - href: balances/general/
          text: 'General'
        - href: balances/material/
          text: 'Material'
        - href: balances/energy/
          text: 'Energy'
        - href: balances/entropy/
          text: 'Entropy'
        - href: balances/exergy/
          text: 'Exergy'
      - href: phase/
        text: 'Phase Equilibria'
      - href: react/
        text: 'Reactors'
      - href: appx/
        text: 'Appendices'
      - text: DOFPro
        menu:
        - href: https://dofpro.org
          text: "DOFPro Home"
        - href: https://dofpro.org/RCK/
          text: "Rocketry"

format:
  html:
    theme: materia
    css: styles.css
    toc: true

execute:
  freeze: auto

