project:
  type: website

website:
  title: "Chemical and Thermal Processes"
  navbar:
    logo: DOFPro_D7_Red_Flame_No_Background_cropped.png
    logo-alt: "DOFPro Logo"
    logo-href: https://dofpro.org
    search: true
    left:
      - href: basics/
      - text: 'Overview'
        menu:
        - href: basics/index.qmd
          text: Overview
        - href: basics/intro/IntroTopicsWebPage.qmd
          text: 'Intro and Disciplines'
        - href: basics/stats/StatsMeasurementsWebPage.qmd
          text: 'Statistics & Measurements'
        - href: basics/calculations/CalculationsWebPage.qmd
          text: 'Calculations'
        - href: basics/processdata/ProcessDataWebPage.qmd
          text: 'Process Data & Variables'
      - text: 'Balances'
        menu:
        - href: balances/general/
          text: 'General'
        - href: balances/material/
          text: 'Material'
        - href: balances/energy/
          text: 'Energy'
        - href: balances/entropy/
          text: 'Entropy'
        - href: balances/exergy/
          text: 'Exergy'
      - href: phase/
        text: 'Phase Equilibria'
      - href: react/
        text: 'Reactors'
      - href: appx/
        text: 'Appendices'
      - text: DOFPro
        menu:
        - href: https://dofpro.org
          text: "DOFPro Home"
        - href: https://dofpro.org/RCK/
          text: "Rocketry"

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

execute:
  freeze: auto

