---
title: "Chemical Reactor Engineering Pathway"
author: "DOFPro group"
format: html
---

# Chemical Reactor Engineering

## Introduction

**From Mole to Megawatt: The Full Journey Through Chemical and Thermal Engineering**<br/>*Intro to DOFPro CTP*<br/>[Video](https://youtu.be/8FEmNkiU1Jk), [Info Page](basics/intro/IntroTopicsWebPage.qmd), [Visuals](basics/intro/1-MoleToMegawattVisuals.qmd)

## Visualize and Calculate

**Is Your Process Data Spread Smooth or Chunky? Just the Facts**<br/>*Data Visualization, linear and Log Coordinates*<br/>[Video](https://youtu.be/yFOrwNmEbPA), [Info Page](basics/calculations/DataVisWebPage.qmd), [Visuals](basics/calculations/DataVisJTFVisuals.qmd)

**Is Your Process Data Spread Smooth or Chunky? The Full Story**<br/>*Data Visualization, linear and Log Coordinates*<br/>[Video](https://youtu.be/VUyyEmif3fs), [Info Page](basics/calculations/DataVisWebPage.qmd), [Visuals](basics/calculations/DataVisTFSVisuals.qmd)

**Interpol Is Late to a Mind-Blowing Math Hack, Just the Facts**<br/>*Linear Interpolation*<br/>[Video](https://youtu.be/VbnpWj9iYAU), [Info Page](basics/calculations/InterpolationWebPage.qmd), [Visuals](basics/calculations/InterpolationJTFVisuals.qmd)

**Interpol Is Late to a Mind-Blowing Math Hack, The Full Story**<br/>*Linear Interpolation*<br/>[Video](https://youtu.be/pbDEc_Q862M), [Info Page](basics/calculations/InterpolationWebPage.qmd), [Visuals](basics/calculations/InterpolationTFSVisuals.qmd)

**No Clear Interpretation a Mind-Blowing Math Hack**<br/>*Nonlinear Interpolation*<br/>[Video](https://youtu.be/721FxKwDRAU), [Info Page](basics/calculations/InterpolationWebPage.qmd), [Visuals](basics/calculations/NLInterpolationJTFVisuals.qmd)

**The Unauthorized Guide to Using Spreadsheets in Chemical Engineering**<br/>*Spreadsheet Basics*<br/>[Video](https://youtu.be/5XMeQ6vWymA), [Info Page](basics/calculations/SpreadsheetTechniquesVideoInfoWebPage.qmd), [Visuals](basics/calculations/BasicSpreadsheetTechniquesJTFVisuals.qmd)

**How to Have a Quickie with Your Data Part 1**<br/>*$\bar{x}$, $S_{\bar{x}}$, Linear Least Squares*<br/>[Video](https://youtu.be/4EfhlWNDQ48), [Info Page](basics/calculations/SpreadsheetTechniquesVideoInfoWebPage.qmd), [Visuals](basics/calculations/Video25Visuals.qmd)

**How to Have a Quickie with Your Data Part 2**<br/>*Nonlinear least squares*<br/>[Video](https://youtu.be/dVmh0EdQT1U), [Info Page](basics/calculations/SpreadsheetTechniquesVideoInfoWebPage.qmd), [Visuals](basics/calculations/Video26Visuals.qmd)

**Solving Nonlinear Equations with Spreadsheets**<br/>*See Title*<br/>[Video](https://youtu.be/SaI2qdu1wSE), [Info Page](basics/calculations/SpreadsheetTechniquesVideoInfoWebPage.qmd), [Visuals](basics/calculations/SolvingNonlinearEQsWithSpreadsheetsJTFVisuals.qmd)

## Types of Process Data

**Is Furlongs Per Fortnight a Thing?**<br/>*Unit Conversion*<br/>[Video](https://youtu.be/5EbL9MEro9E), [Info Page](basics/processdata/DimensionalEquationsWebPage.qmd), [Visuals](basics/processdata/DimensionalEquationsJTFVisuals.qmd)

**How Keen Is Your Rank? Just the Facts**<br/>*Temperature Conversion*<br/>[Video](https://youtu.be/XKwl41MvFcE), [Info Page](basics/processdata/ConvertingTemperatureWebPage.qmd), [Visuals](basics/processdata/ConvertingTemperatureJTFVisuals.qmd)

**How Keen Is Your Rank?, The Full Story**<br/>*Temperature Conversion*<br/>[Video](https://youtu.be/hEtrCnIicqQ), [Info Page](basics/processdata/ConvertingTemperatureWebPage.qmd), [Visuals](basics/processdata/ConvertingTemperatureTFSVisuals.qmd)

**The Most Annoying Equation Conversion**<br/>*Unit Conversion of Equations*<br/>[Video](https://youtu.be/6dyg-CgAm8s), [Info Page](basics/processdata/EquationConversionVideoInfoWebPage.qmd), [Visuals](basics/processdata/EquationConversionJTFVisuals.qmd)

**Where Does Sherwood Hide His Unit? Principles**<br/>*Dimensionless Numbers Principles*<br/>[Video](https://youtu.be/A348vNv5t9c), [Info Page](basics/processdata/DimensionlessNumbersVideoInfoWebPage.qmd), [Visuals](basics/processdata/DimNumPart1JTFVisuals.qmd)

**What the Schmidt? Examples**<br/>*Applications of Dimensionless Numbers*<br/>[Video](https://youtu.be/74SD0k_qBc8), [Info Page](basics/processdata/DimensionlessNumbersVideoInfoWebPage.qmd), [Visuals](basics/processdata/DimNumPart2JTFVisuals.qmd)

**Is It Hot in Here, or Is It Just My Thermistor?**<br/>*Thermistors, Thermocouples, and other Temperature Sensors*<br/>[Video](https://youtu.be/TncEECvmw8Y), [Info Page](basics/processdata/ConvertingTemperatureWebPage.qmd), [Visuals](basics/processdata/32-MeasuringTemperatureVisuals.qmd)

**Under Pressure Part 1, Just the Facts**<br/>*Pressure Basics*<br/>[Video](https://youtu.be/9gbOE5zEt4o), [Info Page](basics/processdata/PressureWebPage.qmd), [Visuals](basics/processdata/PressurePt1JTFVisuals.qmd)

**Under Pressure Part 1, The Full Story**<br/>*Pressure Basics*<br/>[Video](https://youtu.be/D-UAHVi4a2U), [Info Page](basics/processdata/PressureWebPage.qmd), [Visuals](basics/processdata/PressurePt1TFSVisuals.qmd)

**Under Pressure Part 2, Just the Facts**<br/>*Abs., Atm., Gauge, Barometric Pressure*<br/>[Video](https://youtu.be/CR3MomWlqb8), [Info Page](basics/processdata/PressureWebPage.qmd), [Visuals](basics/processdata/PressurePt2JTFVisuals.qmd)

**Under Pressure Part 2, The Full Story**<br/>*Abs., Atm., Gauge, Barometric Pressure*<br/>[Video](https://youtu.be/41axc-xnqsQ), [Info Page](basics/processdata/PressureWebPage.qmd), [Visuals](basics/processdata/PressurePt2TFSVisuals.qmd)

**What is a Mole? Just the Facts**<br/>*What a mole is*<br/>[Video](https://youtu.be/wbEkZmjNtwI), [Info Page](basics/processdata/WhatIsAMoleWebPage.qmd), [Visuals](basics/processdata/WhatIsAMoleJTFVisuals.qmd)

**What is a Mole? The Full Story**<br/>*What a mole is*<br/>[Video](https://youtu.be/CvRsRlpKll8), [Info Page](basics/processdata/WhatIsAMoleWebPage.qmd), [Visuals](basics/processdata/WhatIsAMoleVisuals.qmd)

**What the Frac?**<br/>*Mass, Moles, Mass Fractions, Mole Fractions*<br/>[Video](https://youtu.be/qJERzRm7xc0), [Info Page](basics/processdata/WhatIsAMoleWebPage.qmd), [Visuals](basics/processdata/MassMolesJTFVisuals.qmd)

**Are You Dense? Crank Up the Volume and Go With the Flow! Just the Facts**<br/>*Mass, Moles, Density, Volume, and Flow Rates*<br/>[Video](https://youtu.be/AFZWZSJ96g8), [Info Page](basics/processdata/DensityVolumeFlowVideoInfoWebPage.qmd), [Visuals](basics/processdata/VolumeDensityFlowRateJTFVisuals.qmd)

**Are You Dense? Crank Up the Volume and Go With the Flow!, The Full Story**<br/>*Mass, Moles, Density, Volume, and Flow Rates*<br/>[Video](https://youtu.be/2-EWSUW4BJU), [Info Page](basics/processdata/DensityVolumeFlowVideoInfoWebPage.qmd), [Visuals](basics/processdata/VolumeDensityFlowRateTFSVisuals.qmd)

## General Balances

**How to Keep Your Balance**<br/>*System Definition and the General Balance Equation*<br/>[Video](https://youtu.be/-fjXc-Upxx4), [Info Page](balances/general/index.qmd), [Visuals](balances/general/KeepYourBalanceJTFVisuals.qmd)

**Speed Balancing**<br/>*General Balance Equation Definitions and Suggestions*<br/>[Video](https://youtu.be/Pmp2IxgL9FM), [Info Page](balances/general/index.qmd), [Visuals](balances/general/SpeedBalancingJTFVisuals.qmd)

## Unit Operations and PFDs

**Gotta Keep ‘Em Separated**<br/>*Mixer, Divider, and Separator mole balances*<br/>[Video](https://youtu.be/pRg1m0_9Psg), [Info Page](balances/material/MixDivideSeparateVideoInfoWebPage.qmd), [Visuals](balances/material/40-UnitOpsMixDivSepVisuals.qmd)

**When You Saw It, What Was the Extent of Your Reaction? Part 1**<br/>*Chemical Reactor Single Reaction, $\xi$ and $f_{\mathrm{A}}$*<br/>[Video](https://youtu.be/HKYYp5UxwpA), [Info Page](balances/material/FractionalConversionReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/41-UnitOpsReactPart1Visuals.qmd)

**When You Saw It, What Was the Extent of Your Reaction? Part 2**<br/>*Chemical Reactor Multiple Reactions with Example, $\xi$ and $f_{\mathrm{A}}$*<br/>[Video](https://youtu.be/XmLXR_KOZMk), [Info Page](balances/material/FractionalConversionReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/42-UnitOpsReactPart2Visuals.qmd)

**When You Saw It, What Was the Extent of Your Reaction? Part 3**<br/>*Chemical Reactor Yield and Selectivity*<br/>[Video](https://youtu.be/PPi-ka3iRvI), [Info Page](balances/material/FractionalConversionReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/42.5-UnitOpsReactPart3Visuals.qmd)

**Recycling Before Recycling Was Cool**<br/>*Basics of recycle*<br/>[Video](https://youtu.be/R7tIQyBUWn8), [Info Page](balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](balances/material/43-RecycleBypassPartVisuals.qmd)

**Leaving Radiator Springs In the Dust**<br/>*Basics of bypass and a recycle example*<br/>[Video](https://youtu.be/tjzDu7_n-NI), [Info Page](balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](balances/material/44-RecycleBypassPart2Visuals.qmd)

**The Symbolic Meaning of Recycling**<br/>*Analytic solution of a recycle PFD*<br/>[Video](https://youtu.be/CF18jpqZzgc), [Info Page](balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](balances/material/45-RecycleSymbSolVisuals.qmd)

## Chemical Reactors

**How Did You Think I Would React?**<br/>*Basic Kinetic Reactor Mole Balance*<br/>[Video](https://youtu.be/_qxHszVZYGk), [Info Page](balances/material/KineticReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/46-KineticsIntroJTFVisuals.qmd)

**Wishing Upon a CSTR**<br/>*Batch, CSTR, PFR*<br/>[Video](https://youtu.be/6tnVFq7dSbE), [Info Page](balances/material/KineticReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/47-BatchCSTRPFRIntroVisuals.qmd)

**It’s Totally Tubular, Man!**<br/>*CSTR, PFR, Batch Example*<br/>[Video](https://youtu.be/OAzXx9Kq2nU), [Info Page](balances/material/KineticReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/47.5-ReactorExamplesVisuals.qmd)

**React But Maintain Your Equilibrium Part 1**<br/>*Basics of equilibrium reactors*<br/>[Video](https://youtu.be/0GS8XEHRBMk), [Info Page](balances/material/EquilibriumReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/54-EquilReact1Visuals.qmd)

**React But Maintain Your Equilibrium Part 2**<br/>*Equilibrium reactor example*<br/>[Video](https://youtu.be/GI8tuSRrIcc), [Info Page](balances/material/EquilibriumReactorsVideoInfoWebPage.qmd), [Visuals](balances/material/55-EquilReact2Visuals.qmd)

**Flame On, Torch!**<br/>*Combustion reactions*<br/>[Video](https://youtu.be/G2sKW_6N2BA), [Info Page](balances/material/CombustionReactionsVideoInfoWebPage.qmd), [Visuals](balances/material/59-CombRxnsPart1Visuals.qmd)

**A Combustible Mixture!**<br/>*Sample combustion reactions*<br/>[Video](https://youtu.be/hvIk-evMp88), [Info Page](balances/material/CombustionReactionsVideoInfoWebPage.qmd), [Visuals](balances/material/60-CombRxnsPart2Visuals.qmd)

## 1^st^ Law of Thermodynamics

**Just Try to Break This Law! I Dare You!**<br/>*Intro to 1st Law*<br/>[Video](https://youtu.be/ZHWT9Jw7fzY), [Info Page](balances/energy/Intro1stLawVideoInfoWebPage.qmd), [Visuals](balances/energy/89-Intro1stLawVisuals.qmd)

**Add Friction and Work to Bernoulli? Here’s What Really Happens!**<br/>*The Mechanical Energy Balance and the Moody Chart*<br/>[Video](https://youtu.be/Da48oZb9oNw), [Info Page](balances/energy/MechanicalEnergyBalanceVideoInfoWebPage.qmd), [Visuals](balances/energy/90-MechEngBalVisuals.qmd)

**Reference Not Found: Mixing, Dissolving, and Changing the Rules**<br/>*$\Delta H_m$, $\Delta H_s$*<br/>[Video](https://youtu.be/ggU692PLWts), [Info Page](balances/energy/HeatsOfMixingVideoInfoWebPage.qmd), [Visuals](balances/energy/98-ReferenceStatesVIsuals.qmd)

**The Isochronicles: This First Law Saga Is a Gas**<br/>*The 1^st^ Law for Ideal Gases for Isothermal, Isobaric, Isochoric, and Isentropic processes*<br/>[Video](https://youtu.be/iKsR3v1wu30), [Info Page](balances/energy/The1stLawForIdealGases.qmd), [Visuals](balances/energy/102-1stLawIdealGasesVisuals.qmd)

**Germain Hess and the Enthalpy of Doom**<br/>*Hess's Law and $\Delta \hat{H}^\circ_f$, $\Delta \hat{H}^\circ_r$, and $\Delta \hat{H}c$*<br/>[Video](https://youtu.be/qdgH4v64vOQ), [Info Page](balances/energy/HeatsOfFormationAndReactionVideoInfoWebPage.qmd), [Visuals](balances/energy/104-HeatsOfReactionVisuals.qmd)

**Chemical Reactions vs. The First Law: Who Wins?**<br/>*Forms of the 1^st^ Law for Chemical Reactions*<br/>[Video](https://youtu.be/mFF5hDHclPE), [Info Page](balances/energy/The1stLawReactingSystems.qmd), [Visuals](balances/energy/106-1stLawReactingVisuals.qmd)

**Fueling the Fire: The Shocking Truth About Combustion Reactions!**<br/>*Common fuels, Heats of Combustion, HHV, LHV*<br/>[Video](https://youtu.be/lW5dK-F6H3U), [Info Page](balances/energy/EnergeticsOfCombustionReactionsVideoInfoWebPage.qmd), [Visuals](balances/energy/110-FuelsHeatingVisuals.qmd)

**React Hard: The First Law Gets Chemical**<br/>*Example of the 1^st^ Law for Chemical Reactions*<br/>[Video](https://youtu.be/q-W5Y1d85go), [Info Page](balances/energy/Example1stLawForReactingSystemsVideoInfoWebPage.qmd), [Visuals](balances/energy/111-EnergeticsOfReactionsPt1Visuals.qmd)

**React Harder: Formation Heats and Alternate Endings**<br/>*2 more Examples of the 1^st^ Law for Chemical Reactions*<br/>[Video](https://youtu.be/iqxJP6g-Qsc), [Info Page](balances/energy/Example1stLawForReactingSystemsVideoInfoWebPage.qmd), [Visuals](balances/energy/112-EnergeticsOfReactionsPt2Visuals.qmd)