---
title: "Overview of DOFPro Chemical And Thermal Processes Website"
author: "DOFPro group"
---

# [Current List of Posted Videos](intro/CurrentVideoList.qmd)

The Degrees of Freedom Project is still in the early Alpha stage. It is possible, but extremely difficult, to find links to the currently posted videos on YouTube. To make the process easier while we are in the development process, the list of videos that have been posted on YouTube will be maintained at [this link](intro/CurrentVideoList.qmd). The link will be removed or modified once the full set of videos is available.

# Overview of Chemical and Thermal Processes

## From Mole to Megawatt:<br/>The Full Journey Through<br/>Chemical and Thermal Engineering

Explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/8FEmNkiU1Jk?si=cZl4f3nPPIqWIx1N" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](../../NotYetHere.qmd), [Transcript](../../NotYetHere.qmd) 

## Engineering Principles Discussed

-   Engineering Basics
    -   Statistics, Measurements, and Calculations
    -   Process Data and Variables, such as Pressure, Temperature, Mass, Moles, etc.
    -   Converting among systems of units
    -   Dimensionless numbers
-   System Definition
    -   Open or Closed
    -   Transient or Steady State
-   Material Balances
    -   Mass Balances
    -   Mole Balances
    -   Equations of State and Phase Equilibria
-   Energy Balances or the 1st Law of Thermodynamics
-   Entropy Balances or the 2nd Law of Thermodynamics
-   Thermodynamic Efficiency and the Combined 1st and 2nd Laws

## Why Chemical and Thermal Processes?

The principles in Chemical and Thermal Processes are applicable in

-   [Chemical Engineering](https://en.wikipedia.org/wiki/Chemical_engineering)
-   [Petroleum Engineering](https://en.wikipedia.org/wiki/Petroleum_engineering)
-   [Mechanical Engineering](https://en.wikipedia.org/wiki/Mechanical_engineering)
-   [Materials Engineering](https://en.wikipedia.org/wiki/Materials_science)
-   [Bioengineering](https://en.wikipedia.org/wiki/Biological_engineering)
-   [Environmental Engineering](https://en.wikipedia.org/wiki/Environmental_engineering)
-   [Energy Engineering](https://en.wikipedia.org/wiki/Energy_engineering)
-   [Sustainability](https://en.wikipedia.org/wiki/Sustainability)
-   [Manufacturing Engineering](https://en.wikipedia.org/wiki/Manufacturing_engineering)
-   [Industrial Engineering](https://en.wikipedia.org/wiki/Industrial_engineering)
-   [Marine](https://en.wikipedia.org/wiki/Marine_engineering) and [Aerospace Engineering](https://en.wikipedia.org/wiki/Aerospace_engineering)