---
title: "*Cp* and ∆*H* Estimates Reference Page<br/>*Feeling the Heat? How to Get Your Best Estimate*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
{{< include /LinkKey.qmd >}}
# Intro to *Feeling the Heat? How to Get Your Best Estimate*

In many thermodynamic problems, accurate property data may not be available for the exact substance or temperature range needed. In these situations, engineers often rely on **estimation methods** to approximate heat capacities and enthalpy changes.

These methods can provide surprisingly useful results with very little information. This video introduces several commonly used estimation techniques, including Kopp's rule, Trouton's rule, and correlations for estimating heats of vaporization.

## Feeling the Heat? How to Get Your Best Estimate

This video explains several useful methods for estimating heat capacities and enthalpy changes when detailed thermodynamic data are not available.

<iframe width="560" height="315" src="https://www.youtube.com/embed/f_l3OFyuiPs?si=_1ezGSzwq62Jo2Vc" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](95-EstimatingHeatCapacitiesVisuals.qmd)

# Examples and Definitions

## Examples Links

## Definitions

[Kopp's Rule](https://en.wikipedia.org/wiki/Kopp%27s_law)  
: A rule for estimating the heat capacity of a compound by summing the approximate contributions from the atoms present in the molecule.

[Sensible Heat Changes](https://en.wikipedia.org/wiki/Sensible_heat)  
: Temperature changes that occur when heat is added to or removed from a substance without a phase change.

[Latent Heat](https://en.wikipedia.org/wiki/Latent_heat)  
: Heat absorbed or released by a substance during a phase change at constant temperature.

[Trouton's Rule](https://en.wikipedia.org/wiki/Trouton%27s_rule)  
: An empirical rule used to estimate the **enthalpy of vaporization** of many liquids from their normal boiling temperature and the **enthalpy of fusion** of many solids from their normal melting temperature.

[Clausius-Clapeyron Equation](https://en.wikipedia.org/wiki/Clausius%E2%80%93Clapeyron_relation)  
: An equation relating vapor pressure to temperature and the enthalpy of vaporization:

$$
\ln p^* = -\frac{\Delta H_v}{RT} + B
$$

[Watson Correlation](https://personal.ems.psu.edu/~radovic/Watson_IEC_1943.pdf)  
: A correlation used to estimate the enthalpy of vaporization at one temperature from its value at another temperature using the critical temperature. A related expression is the [Shimansky equation](https://en.wikipedia.org/wiki/Shimansky_equation).

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**The Enthalpy Games: The Ballad of Integrals and Means**<br/>*$\Delta H$ from $C_p$, $\Delta U$ from $C_v$*<br/>[Video](https://youtu.be/YGMHMAXnFY8), [Info Page](../../balances/energy/HeatCapacityVideoInfoWebPage.qmd), [Visuals](../../balances/energy/93-EnthalpyVsTandPPart1.qmd)

### Previous video

**The Enthalpy Games: Sunrise on the Calculations**<br/>*Example for $\mathrm{N_2}$, $\Delta H$ from $C_p$, $\Delta U$ from $C_v$*<br/>[Video](https://youtu.be/yLJp3YQaVvo), [Info Page](../../balances/energy/HeatCapacityVideoInfoWebPage.qmd), [Visuals](../../balances/energy/94-EnthalpyVsTandPPart2.qmd)

### Next video

**Dry Bulbs, Wet Bulbs, and My Will to Live: Mastering the Psych Chart**<br/>*Psychrometric Charts*<br/>[Video](https://youtu.be/Nz8ADo4X2Ss), [Info Page](../../balances/energy/PsychrometricChartsVideoInfoWebPage.qmd), [Visuals](../../balances/energy/97-PsychrometiricChartVIsuals.qmd)

### Two videos forward

**Reference Not Found: Mixing, Dissolving, and Changing the Rules**<br/>*$\Delta H_m$, $\Delta H_s$*<br/>[Video](https://youtu.be/ggU692PLWts), [Info Page](../../balances/energy/HeatsOfMixingVideoInfoWebPage.qmd), [Visuals](../../balances/energy/98-ReferenceStatesVIsuals.qmd)