---
title: "Steam Tables Reference Page<br/>*Steam: Get the Quality Right AFTER You Table It!*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
{{< include /LinkKey.qmd >}}
# Intro to Steam Tables

Steam tables are one of the most widely used engineering tools for applying the First Law of Thermodynamics. They provide tabulated thermodynamic properties of water in its liquid, vapor, and two-phase states.

Because water is such an important working fluid in power plants, refrigeration systems, and many industrial processes, its properties have been measured and standardized in great detail. Engineers use steam tables to determine quantities such as enthalpy, internal energy, entropy, and specific volume for saturated and superheated steam.

The videos on this page explain how steam tables are organized and how to use them to solve thermodynamic problems.

## Steam: Get the Quality Right AFTER You Table It! Part 1

This video introduces steam tables and explains how to interpret the saturated-property tables. It also introduces the concept of **quality**, which describes the fraction of vapor present in a liquid–vapor mixture.

<iframe width="560" height="315" src="https://www.youtube.com/embed/8tH3gXz_M8A?si=ZSnLBeA9c4uXRMsC" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](91-ThermodynamicPropertyTables1Visuals.qmd)

## Steam: Get the Quality Right AFTER You Table It! Part 2

This video shows how to use steam tables to solve practical thermodynamic problems, including determining properties in the saturated and superheated regions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/yRf09eSRM1A?si=Ti4C8E1i9Rd9oXS0" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](92-ThermodynamicPropertyTables2Visuals.qmd)

# Examples and Definitions

## Examples Links

- [Steam Tables](https://dofprobucket1.s3.us-east-2.amazonaws.com/energy/SteamTables.ods) – Spreadsheet containing steam tables in SI units generated by DWSIM using the **IAPWS-IF97** standard.

## Definitions

Steam Table  
: A tabulation of thermodynamic properties of water in its saturated liquid, saturated vapor, and superheated vapor states. Saturated properties are tabulated as a function of either temperature or pressure, while superheated properties require both temperature and pressure to determine the state.  

The tabulated properties typically include specific volume $\hat{V}$, specific internal energy $\hat{U}$, specific enthalpy $\hat{H}$, and specific entropy $\hat{S}$.

Quality, $x$
: The mass fraction of vapor in a saturated liquid–vapor mixture.

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**Just Try to Break This Law! I Dare You!**<br/>*Intro to 1st Law*<br/>[Video](https://youtu.be/ZHWT9Jw7fzY), [Info Page](../../balances/energy/Intro1stLawVideoInfoWebPage.qmd), [Visuals](../../balances/energy/89-Intro1stLawVisuals.qmd)

### Previous video

**Add Friction and Work to Bernoulli? Here’s What Really Happens!**<br/>*The Mechanical Energy Balance and the Moody Chart*<br/>[Video](https://youtu.be/Da48oZb9oNw), [Info Page](../../balances/energy/MechanicalEnergyBalanceVideoInfoWebPage.qmd), [Visuals](../../balances/energy/90-MechEngBalVisuals.qmd)

### Next video

**The Enthalpy Games: The Ballad of Integrals and Means**<br/>*$\Delta H$ from $C_p$, $\Delta U$ from $C_v$*<br/>[Video](https://youtu.be/YGMHMAXnFY8), [Info Page](../../balances/energy/HeatCapacityVideoInfoWebPage.qmd), [Visuals](../../balances/energy/93-EnthalpyVsTandPPart1.qmd)

### Two videos forward

**The Enthalpy Games: Sunrise on the Calculations**<br/>*Example for $\mathrm{N_2}$, $\Delta H$ from $C_p$, $\Delta U$ from $C_v$*<br/>[Video](https://youtu.be/yLJp3YQaVvo), [Info Page](../../balances/energy/HeatCapacityVideoInfoWebPage.qmd), [Visuals](../../balances/energy/94-EnthalpyVsTandPPart2.qmd)