---
title: "The 1^st^ Law for Ideal Gases Reference Page<br/>*The Isochronicles: This First Law Saga Is a Gas*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
{{< include /LinkKey.qmd >}}
# Intro to The 1^st^ Law for Ideal Gases

Ideal gases provide one of the simplest and most useful applications of the First Law of Thermodynamics. Because the thermodynamic properties of ideal gases have simple relationships, many energy balances can be solved analytically.

In particular, the First Law can be applied to several important types of processes: constant temperature, constant pressure, constant volume, and constant entropy. These special cases appear frequently in engineering calculations involving compressors, turbines, and expansion processes.

## The Isochronicles: This First Law Saga Is a Gas

This video shows how the First Law of Thermodynamics applies to ideal gases undergoing common thermodynamic processes, including isothermal, isobaric, isochoric, and isentropic processes.

<iframe width="560" height="315" src="https://www.youtube.com/embed/iKsR3v1wu30?si=jNOfKbT6n2jMDehd" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](102-1stLawIdealGasesVisuals.qmd)

# Examples and Definitions

## Examples Links

## Definitions

[Isothermal Process](https://en.wikipedia.org/wiki/Isothermal_process)  
: A constant-temperature process, $\Delta T = 0$.

[Isobaric Process](https://en.wikipedia.org/wiki/Isobaric_process)  
: A constant-pressure process, $\Delta P = 0$.

[Isochoric Process](https://en.wikipedia.org/wiki/Isochoric_process)  
: A constant-volume process, $\Delta V = 0$.

[Isentropic Process](https://en.wikipedia.org/wiki/Isentropic_process)  
: A constant-entropy process, $\Delta S = 0$.  

Historically, Clausius used the term to refer to processes that are **adiabatic and reversible**, and most thermodynamics texts still use the term in that sense.

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**Dry Bulbs, Wet Bulbs, and My Will to Live: Mastering the Psych Chart**<br/>*Psychrometric Charts*<br/>[Video](https://youtu.be/Nz8ADo4X2Ss), [Info Page](../../balances/energy/PsychrometricChartsVideoInfoWebPage.qmd), [Visuals](../../balances/energy/97-PsychrometiricChartVIsuals.qmd)

### Previous video

**Reference Not Found: Mixing, Dissolving, and Changing the Rules**<br/>*$\Delta H_m$, $\Delta H_s$*<br/>[Video](https://youtu.be/ggU692PLWts), [Info Page](../../balances/energy/HeatsOfMixingVideoInfoWebPage.qmd), [Visuals](../../balances/energy/98-ReferenceStatesVIsuals.qmd)

### Next video

**Germain Hess and the Enthalpy of Doom**<br/>*Hess's Law and $\Delta \hat{H}^\circ_f$, $\Delta \hat{H}^\circ_r$, and $\Delta \hat{H}_c$*<br/>[Video](https://youtu.be/qdgH4v64vOQ), [Info Page](../../balances/energy/HeatsOfFormationAndReactionVideoInfoWebPage.qmd), [Visuals](../../balances/energy/104-HeatsOfReactionVisuals.qmd)

### Two videos forward

**Chemical Reactions vs. The First Law: Who Wins?**<br/>*Forms of the 1^st^ Law for Chemical Reactions*<br/>[Video](https://youtu.be/mFF5hDHclPE), [Info Page](../../balances/energy/The1stLawReactingSystems.qmd), [Visuals](../../balances/energy/106-1stLawReactingVisuals.qmd)