---
title: "Data Visualization Web Page<br/>*Is Your Process Data Spread Smooth or Chunky?*"
author: "DOFPro group"
format: html
---
# Key to the Videos and Links

- **JTF (Just the Facts)** videos are the streamlined versions: greenscreen LaTeX equations, clean graphics, minimal narrative. Think “efficient and to the point.” Each has a companion TFS video.
- **TFS (The Full Story)** videos include interviews, additional explanation, and equations written on whiteboards. Same math, more context, more personality. Each has a matching JTF version.
- **Info Page** links lead to definitions, expanded explanations, and related material—because sometimes you really do need to explain it.
- **Visuals** links contain the underlying greenscreen or whiteboard materials used in the video, for those who like to see the scaffolding.
- Wondering about the titles? See Appendix B: [**If you have to explain it, it’s no longer funny**](../../appx/NotFunny.qmd)￼.


# Purpose of Data Visualization<br/>*Is Your Process Data Spread Smooth or Chunky?*

Presentation and analysis of process data from Chemical and Thermal Processes is one of the fundamental activities for Process Engineers. For determining the functional form of a data set, it turns out that the human visual system is very good at seeing if the trend in a plot of data is a straight line or almost a straight line. If your data plot doesn’t appear as a straight line, it’s possible that a change of coordinates will make it appear as a straight line. This video discusses common transformation of coordinates to make your data set appear straight.

## Just The Facts

The *Just The Facts* Video discusses data presentation techniques and plotting and explains how to transform coordinates to get linear, semi-log and log-log plots, and how to calculate model parameters from the data. It is recommended for those who have a reasonably good understanding of data visualization and coordinate transformation and are just looking for a refresher or a review.

<iframe width="560" height="315" src="https://www.youtube.com/embed/yFOrwNmEbPA?si=aIY5p3Mt4_Uf4BO1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](DataVisJTFVisuals.qmd)

## The Full Story

*The Full Story* Video examines common conceptions and misconceptions about data presentation and plotting and explains how to transform coordinates to get linear, semi-log and log-log plots, and how to calculate model parameters from the data. It is recommended for those who have not been exposed to data plotting and coordinate transformations before or who have struggled with understanding and performing the transformations and calculations.

<iframe width="560" height="315" src="https://www.youtube.com/embed/VUyyEmif3fs?si=HOz_bhZ4vFiPckNU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](DataVisTFSVisuals.qmd)

# Examples and Definitions

## Examples Links

- [Data Visualization Plot Demo](https://dofprobucket1.s3.us-east-2.amazonaws.com/calculations/DataVisPlotDemo.ods) – A spreadsheet demonstrating the techniques in the video

## Definitions

[Data Visualization](https://en.wikipedia.org/wiki/Data_and_information_visualization)
: The process of presenting or plotting your data to make trends and functional behavior more obvious.

[Linear Plot](https://www.cuemath.com/data/linear-graph/)
: A plot where the $x$ and $y$ coordinates are both on a linear scale. The data plot may or may not appear as a straight line depending on how close the data come to fitting the equation of a line.

[Semi-log plot](https://en.wikipedia.org/wiki/Semi-log_plot)
: A plot where either the $x$-coordinate scale is linear and the $y$-coordinate scale is logarithmic or the data are plotted as $\log y$ versus $x$ on linear scales. The data plot may or may not appear as a straight line depending on how close the data come to fitting the equation of an exponential function.

[Log-Log Plot](https://en.wikipedia.org/wiki/Log%E2%80%93log_plot)
: A plot where either the $x$-coordinate scale and the $y$-coordinate scales are both logarithmic or the data are plotted as $\log y$ versus $\log x$ on linear scales. The data plot may or may not appear as a straight line depending on how close the data come to fitting a power law.

[Exponential Function](https://en.wikipedia.org/wiki/Exponential_function)
: A function of the form $y = ae^{bx}$ or $y = a10^{bx}$ where $a$ and $b$ are constants.

[Power Law](https://en.wikipedia.org/wiki/Power_law)
: A function of the form $y = ax^b$ where $a$ and $b$ are constants.

[Nonlinear Least-Squares Fit](https://en.wikipedia.org/wiki/Non-linear_least_squares)
: The process of fitting data to a function that is not linear in the fitting parameters without a change of variables. It must usually be done with a computer.

# Other Links and Videos

## Other Links

## Previous and Following Videos

### The previous video (i.e., one video back)

**From Mole to Megawatt: The Full Journey Through Chemical and Thermal Engineering**<br/>*Intro to DOFPro CTP*<br/>[Video](https://youtu.be/8FEmNkiU1Jk), [Info Page](../../basics/intro/IntroTopicsWebPage.qmd), [Visuals](../../basics/intro/1-MoleToMegawattVisuals.qmd)

### The next video (i.e., one video forward)

**Interpol Is Late to a Mind-Blowing Math Hack, Just the Facts**<br/>*Linear Interpolation*<br/>[Video](https://youtu.be/VbnpWj9iYAU), [Info Page](../../basics/calculations/InterpolationWebPage.qmd), [Visuals](../../basics/calculations/InterpolationJTFVisuals.qmd)

### The next after next video (i.e. two videos forward)

**No Clear Interpretation a Mind-Blowing Math Hack**<br/>*Nonlinear Interpolation*<br/>[Video](https://youtu.be/721FxKwDRAU), [Info Page](../../basics/calculations/InterpolationWebPage.qmd), [Visuals](../../basics/calculations/NLInterpolationJTFVisuals.qmd)








