---
title: "Current List of Videos on YouTube"
author: "DOFPro group"
format: html
---

Links to the current videos on YouTube will be maintained here. These are current as of 2025-08-01.

# Table of Videos

| Vid. \# | Title | JTF Link | TFS Link | Info Page | Subject|
|---------|-------|----------|----------|-----------|--------|
| 5 | How Deviant and Mean Are Your Data? Intro and Basics Part 1 | [Link](https://youtu.be/ksg4Babav6o) | No | [Page](../stats/BasicStatisticsWebPage.qmd) | Mean ($\mu,\ \bar{x}$) and Standard Deviation ($\sigma,\ S$)|
| 5A | How Deviant and Mean Are Your Data? Part 2 | [Link](https://youtu.be/cBOrE6eV-AE) | No | [Page](../stats/BasicStatisticsWebPage.qmd) | Standard Error ($S_{\bar{x}}$) and Confidence Interval ($2\lambda$) |
| 6 | Basics Statistics by Hand | [Link](https://youtu.be/h7WoWiVLzaw) |  No | [Page](../stats/BasicStatisticsWebPage.qmd) | $\bar{x}$, $S$, $S_{\bar{x}}$, $\lambda$ by hand|
| 7 | Basic Statistics on a Spreadsheet | [Link](https://youtu.be/RZ1kFVLvSxY) |  No | [Page](../stats/BasicStatisticsWebPage.qmd) | $\bar{x}$, $S$, $S_{\bar{x}}$, $\lambda$ with a spreadsheet|
| 9 | Basic Statistics in R | [Link](https://youtu.be/va7O78QdYLk) |  No | [Page](../stats/BasicStatisticsWebPage.qmd) | $\bar{x}$, $S$, $S_{\bar{x}}$, $\lambda$ in R|
| 21 | Is Your Process Data Spread Smooth or Chunky? | [Link](https://youtu.be/yFOrwNmEbPA) | No | [Page](../calculations/DataVisWebPage.qmd) | Data Visualization, linear and Log Coordinates |
| 22 | Interpol Is Late to a Mind-Blowing Math Hack | [Link](https://youtu.be/VbnpWj9iYAU) | No | [Page](../calculations/InterpolationWebPage.qmd) | Linear Interpolation |
| 23 | No Clear Interpretation a Mind-Blowing Math Hack | [Link](https://youtu.be/721FxKwDRAU) | No | [Page](../calculations/InterpolationWebPage.qmd) | Nonlinear Interpolation |
| 25 | How to Have a Quickie with Your Data Part 1 | [Link](https://youtu.be/4EfhlWNDQ48) | No | [Page] | $\bar{x}$, $S_{\bar{x}}$, Linear Least Squares |
| 26 | How to Have a Quickie with Your Data Part 2 | [Link](https://youtu.be/dVmh0EdQT1U) | No | [Page]| Nonlinear least squares |
| 27 | Is Furlongs Per Fortnight a Thing? | [Link](https://youtu.be/5EbL9MEro9E) | No | [Page](../processdata/DimensionalEquationsWebPage.qmd) | Unit Conversion |
| 28 | How Keen Is Your Rank? | [Link](https://youtu.be/XKwl41MvFcE) | No | [Page](../processdata/ConvertingTemperatureWebPage.qmd) | Temperature Conversion |
| 29 | The Most Annoying Equation Conversion | [Link](https://youtu.be/6dyg-CgAm8s) | No | [Page] | Unit Conversion of Equations |
| 30 | Where Does Sherwood Hide His Unit? Principles| [Link](https://youtu.be/A348vNv5t9c)| No | [Page] | Dimensionless Numbers Principles |
| 31 | What the Schmidt? Examples | [Link](https://youtu.be/74SD0k_qBc8) | No | [Page] | Applications of Dimensionless Numbers |
| 33 | Under Pressure Part 1 | [Link](https://youtu.be/9gbOE5zEt4o) | No | [Page](../processdata/PressureWebPage.qmd) | Pressure Basics |
| 34 | Under Pressure Part 2 | [Link](https://youtu.be/CR3MomWlqb8) | No | [Page](../processdata/PressureWebPage.qmd) | Abs., Atm., Gauge, Barometric Pressure |
| 35 | What is a Mole? | [Link](https://youtu.be/wbEkZmjNtwI) | [Link](https://youtu.be/CohvkBV_iWA) | [Page](../processdata/WhatIsAMoleWebPage.qmd) | What a mole is |
| 36 | What the Frac? | [Link](https://youtu.be/JPGhnx8NUKQ) | No | [Page](../processdata/MassMolesWebPage.qmd) | Mass, Moles, Mass Fractions, Mole Fractions |
| 37 | Are You Dense? Crank Up the Volume and Go With the Flow! | [Link](https://youtu.be/AFZWZSJ96g8) | No | [Page] | Mass, Moles, Density, Volume, and Flow Rates|
| 38 | How to Keep Your Balance | [Link](https://youtu.be/-fjXc-Upxx4) | No | [Page] | System Definition and the General Balance Equation|
| 39 | Speed Balancing | [Link](https://youtu.be/Pmp2IxgL9FM) | No | [Page] | General Balance Equation Definitions and Suggestions|
| 40 | Gotta Keep ‘Em Separated | [Link](https://youtu.be/pRg1m0_9Psg) | No | [Page] | Mixer, Divider, and Separator mole balances|
| 41 | When You Saw It, What Was the Extent of Your Reaction? Part 1 | [Link](https://youtu.be/HKYYp5UxwpA) | No | [Page] | Chemical Reactor Single Reaction, $\xi$ and $f_{\mathrm{A}}$|
| 42 | When You Saw It, What Was the Extent of Your Reaction? Part 2 | [Link](https://youtu.be/XmLXR_KOZMk) | No | [Page] | Chemical Reactor Multiple Reactions with Example, $\xi$ and $f_{\mathrm{A}}$|
| 42A | When You Saw It, What Was the Extent of Your Reaction? Part 3 | [Link](https://youtu.be/PPi-ka3iRvI) | No | [Page] | Chemical Reactor Yield and Selectivity|
| 43 | Recycling Before Recycling Was Cool | [Link](https://youtu.be/R7tIQyBUWn8) | No | [Page] | Basics of recycle|
| 44 | Leaving Radiator Springs In the Dust | [Link](https://youtu.be/tjzDu7_n-NI) | No | [Page] | Basics of Bypass and a Recycle example|
| 45 | The Symbolic Meaning of Recycling | [Link](https://youtu.be/CF18jpqZzgc) | No | [Page] | Analytic solution of a recycle PFD|
| 46 | How Did You Think I Would React? | [Link](https://youtu.be/_qxHszVZYGk) | No | [Page] | Basic Kinetic Reactor Mole Balance|
| 47 | Wishing Upon a CSTR | [Link](https://youtu.be/6tnVFq7dSbE) | No | [Page] | Batch, CSTR, PFR|
| 47A | It’s Totally Tubular, Man! | [Link](https://youtu.be/OAzXx9Kq2nU) | No | [Page] | CSTR, PFR, Batch Example|
| 54 | React But Maintain Your Equilibrium Part 1 | [Link](https://youtu.be/0GS8XEHRBMk) | No | [Page] | Basics of equilibrium reactors|
| 55 | React But Maintain Your Equilibrium Part 2 | [Link](https://youtu.be/GI8tuSRrIcc) | No | [Page] | Equilibrium reactor example|
| 59 | Flame On, Torch! | [Link](https://youtu.be/G2sKW_6N2BA) | No | [Page] | Equilibrium reactor example|
| 60 | A Combustible Mixture! | [Link](https://youtu.be/hvIk-evMp88) | No | [Page] | Equilibrium reactor example|
| 61 | Alcohol and Water DO Mix! | [Link](https://youtu.be/_tjYMjWR4fE) | No | [Page] | Liquid and Solid Density Calculations |
| 62 | Ideal Gases EXPOSED: Are They Even Real?!! | [Link](https://youtu.be/L-DEw6dGRps) | No | [Page] | Basics of $P V = n R T$|
| 63 | When Getting Gassed Isn’t Ideal, Part 1 | [Link](https://youtu.be/1sU4_YdcKr4) | No | [Page] | Real gas intro |
| 64 | When Getting Gassed Isn’t Ideal, Part 2 | [Link](https://youtu.be/Q6ZK_Ou967o) | No | [Page] | Real gas example |
| 65 | REAL Gas Mixtures EXPLAINED – Don’t Let This Cost You Points on Your Exam! Part 1 | [Link](https://youtu.be/yI3jj1jCSAM) | No | [Page] | Explanation of Kay's Rule and DWSIM for real gas mixtures |
| 66 | REAL Gas Mixtures EXPLAINED – Don’t Let This Cost You Points on Your Exam! Part 2 | [Link](https://youtu.be/Pbizi39c1Rk) | No | [Page] | Example of Kay's Rule and DWSIM for real gas mixtures |
| 67 | Solving Nonlinear Equations with Spreadsheets | [link](https://youtu.be/SaI2qdu1wSE) | No | [Page] | See Title |
| 72 | Show Some Flash and Dew the Dew with a Little Bubbly! | [link](https://youtu.be/shKvpcsJIEM) | No | [Page] | Graphical BUBL P, DEW P, BUBL T, DEW T, and FLASH calculations |
| 73 | Oh, Henry! | [link](https://youtu.be/dCOQy1C7yf0) | No | [Page] | Gas-Liquid Equilibrium with one condensible component |
| 74 | Dew Your Bubbles Have Flash? Part 1 | [Link](https://youtu.be/vSkSRi6HYVQ) | No | [Page] | Raoult's law, BUBL P, DEW P |
| 75 | Dew Your Bubbles Have Flash? Part 2 | [Link](https://youtu.be/9GyrfJzg-tg) | No | [Page] | BUBL T, DEW T |
| 75A| Dew Your Bubbles Have Flash? Part 3 | [Link](https://youtu.be/bG15qQ9gB4c) | No | [Page] | FLASH, *Pxy*, *Txy* |
| 85| The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 1 | [Link](https://youtu.be/bY9fl5DJzmk) | No | [Page] | Equilibrium Stage Equations |
| 86| The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 2 | [Link](https://youtu.be/wc6gv7lNtI0) | No | [Page] | Distillation Examples: Binary Phase Diagram, Raoult's law |
| 86A| The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 3 | [Link](https://youtu.be/jcChVoELvFo) | No | [Page] | Liquid-Liquid Extraction Example |
| 88| Using DWSIM to Create Binary Phase Diagrams | [Link](https://youtu.be/5NUchIg8q7E) | No | [Page] | DWSIM, Binary Phase Diagrams |
| 89| Just Try to Break This Law! I Dare You!  | [Link](https://youtu.be/ZHWT9Jw7fzY) | No | [Page] | Intro to 1st Law |
| 90| Add Friction and Work to Bernoulli? Here’s What Really Happens!  | [Link](https://youtu.be/Da48oZb9oNw) | No | [Page] | The Mechanical Energy Balance and the Moody Chart |
| 91| Steam: Get the Quality Right AFTER You Table It! Part 1  | [Link](https://youtu.be/8tH3gXz_M8A) | No | [Page] | The Basics of Steam Tables |
| 92| Steam: Get the Quality Right AFTER You Table It! Part 2  | [Link](https://youtu.be/yRf09eSRM1A) | No | [Page] | Steam Table Examples |
| 95| Feeling the Heat? How to Get Your Best Estimate | [Link](https://youtu.be/f_l3OFyuiPs) | No | [Page] | Estimating $C_p$, $\Delta \hat{H}_v$, $\Delta \hat{H}_m$ |
| 104| Germain Hess and the Enthalpy of Doom  | [Link](https://youtu.be/qdgH4v64vOQ) | No | [Page] | Hess's Law and $\Delta \hat{H}^\circ_f$, $\Delta \hat{H}^\circ_r$, and $\Delta \hat{H}c$ |
| 110| Fueling the Fire: The Shocking Truth About Combustion Reactions! | [Link](https://youtu.be/lW5dK-F6H3U) | No | [Page] | Common fuels, Heats of Combustion, HHV, LHV |
| 115| The ΔS-sentials of Calculating Entropy Changes  | [Link](https://youtu.be/z2e5Rq5r288) | No | [Page] | Calculating $\Delta S$ for heat reservoirs, ideal gases, and Steam |
| 117| How Much Entropy Can You Balance on the Head of a Pin (or in an Open Steady-State System)?  | [Link](https://youtu.be/QcZTezMtDRk) | No | [Page] | The 2nd Law for Closed, Open Steady-State, and Open Transient Systems |
