---
title: "If You Have to Explain It, It’s No Longer Funny"
author: "DOFPro group"
---

Here are the Eater Eggs, References, and thngs you might have missed in in the titles to the DOFPro CTP videos:

 - [A Combustible Mixture!](../NotYetHere.qmd): This is a clickbait-style and punny title. The phrase is usually used to describe what happens when you have certain people and/or subject matters together and an argument or violence ensues. In this case, it is actually describing chemical mixtures that are designed to combust or burn.
 - [Add Friction and Work to Bernoulli? Here’s What Really Happens!](../NotYetHere.qmd): "Here's what *really* happens!" is a popular phrase in clickbait. Bernoulli's equation is much more famous than the mechanical energy balance, and the video starts with the mechanical energy balance and then includes the Bernoulli equation as a simplification by removing the friction and the shaft work.
 - [Alcohol and Water DO Mix!](../NotYetHere.qmd): The phrase, "Alcohol and *X* Don't Mix", where *X* can be anything from driving to pregnancy, to eating morel mushrooms is a common exhortation to not mix them. The video describes how to estimate the density or specific volume of chemical mixtures, and the main example is alcohol and water, whose mixtures are very non-ideal.
 - [Are You Dense? Crank Up the Volume and Go With the Flow!](../NotYetHere.qmd): "Are you dense?" is a good clickbait phrase, as a re "Crank up the volume!" and "Go with the flow!". Since the video describes the concepts of specific and molar density and specific and molar volume, along with mass, molar, and volumetric flow rates, the title seemed appropriate.
 - [Basic Statistics by Hand](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to do basic statistical calculations by hand. If you have a good or amusing alternate title, put it in the comments.
 - [Basic Statistics in R](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to do basic statistical calculations with the statistics language *R*. If you have a good or amusing alternate title, put it in the comments.
 - [Basic Statistics on a Spreadsheet](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to do basic statistical calculations with with a spreadsheet. If you have a good or amusing alternate title, put it in the comments.
 - [Boil, Expand, Condense, Repeat: The Rankine Cycle in Action Part 1](../NotYetHere.qmd): This title is meant to invoke memories of several different phrases, including *Live, Love, Laugh*, *Lather, Rinse, Repeat*, and *Live, Die, Repeat* the original title of *Edge of Tomorrow*. Since the Rankine cycle is a cyclic process, you repeat every step ad infinitum.
 - [Boil, Expand, Condense, Repeat: The Rankine Cycle in Action Part 2](../NotYetHere.qmd): This title is a repeat of a cyclic title that is meant to invoke memories of several different phrases, including *Live, Love, Laugh*, *Lather, Rinse, Repeat*, and *Live, Die, Repeat* the original title of *Edge of Tomorrow*. Since the Rankine cycle is a cyclic process, you repeat every step ad infinitum.
 - [Can You Tell an Azeotrope from a Peritectic? Get Your Phase Diagrams Right! Part 1](../NotYetHere.qmd): "Get your *X* right!", where *X* can be anything from *notes* and/or *rhythms* to *your head* is a popular clickbait phrase. Azeotropes and peritectics are words that most people wouldn't recognize but play a big role in binary phase diagrams, so the title arouses the curiosity of the viewer. People who are actually looking for azeotropes, peritectics, and binary phase diagrams will find the clickbait title amusing.
 - [Can You Tell an Azeotrope from a Peritectic? Get Your Phase Diagrams Right! Part 1](../NotYetHere.qmd):  "Get your *X* right!", where *X* can be anything from *notes* and/or *rhythms* to *your head* is a popular clickbait phrase. Azeotropes and peritectics are words that most people wouldn't recognize but play a big role in binary phase diagrams, so the title arouses the curiosity of the viewer. People who are actually looking for azeotropes, peritectics, and binary phase diagrams will find the clickbait title amusing.
 - [Chemical Reactions vs. The First Law: Who Wins?](../NotYetHere.qmd): "Who wins?" is a popular clickbait phrase. The video describes applying the First Law of Thermodynamics to a reactive process, so the title doesn't really make sense, but someone might be curious to see if one of them does win.
 - [Cycle Wars: The Power Awakens](../NotYetHere.qmd): A direct rip-off of *Star Wars: The Force Awakens* as applied to air-standard power cycles. We're still within fair-use guidelines.
 - [Cycle Wars: The Rise of Otto Cycles](../NotYetHere.qmd): A direct rip-off of *Star Wars: The Rise of Skywalker* as applied to the *Otto cycle* and other air-standard power cycles. We're still within fair-use guidelines.
 - [Dew Your Bubbles Have Flash? Part 1](../NotYetHere.qmd): The three most common calculations in vapor-liquid phase equilibrium calculations are the *bubble point*, the *dew point*, and the *flash* calculations. This title combines the *Do the dew* spelling of *do* with the clickbait-rich words *bubbles* and *flash*.
 - [Dew Your Bubbles Have Flash? Part 2](../NotYetHere.qmd): The three most common calculations in vapor-liquid phase equilibrium calculations are the *bubble point*, the *dew point*, and the *flash* calculations. This title combines the *Do the dew* spelling of *do* with the clickbait-rich words *bubbles* and *flash*.
 - [Dew Your Bubbles Have Flash? Part 2](../NotYetHere.qmd): The three most common calculations in vapor-liquid phase equilibrium calculations are the *bubble point*, the *dew point*, and the *flash* calculations. This title combines the *Do the dew* spelling of *do* with the clickbait-rich words *bubbles* and *flash*.
 - [Dry Bulbs, Wet Bulbs, and My Will to Live: Mastering the Psych Chart](../NotYetHere.qmd): Psychrometric charts are one of the traditionally most difficult part of a thermodynamics or HVAC course. We wanted to reference how people struggle with psychrometric charts, how they usually involve dry-bulb and wet-bulb thermometric measurements, as well as exploit the human fascination with psychiatry and how both *psychiatry* and *psychrometry* could both be abbreviated as *psych*. Did we *psych* you out? Well, it was intentional. Sorry-Not Sorry!
 - [Entropy Made Me Do It: Pumps, Nozzles, and Other Second-Law Shenanigans](../NotYetHere.qmd): Many students find the concept of entropy to be the devil incarnate, so replacing *The Devil made me do it* with *Entropy made me do it* seemed fitting. Also, since an increase in entropy is responsible for so much in the universe, the title made thermodynamic sense as well. Listing several devices that are analyzed using the Second Law and referring to them as Shenanigans seemed to fit the whole entropy-as-the-devil theme.
 - [Entropy Made Me Do It: Turbines, Compressors, and Other Second-Law Shenanigans](../NotYetHere.qmd): Many students find the concept of entropy to be the devil incarnate, so replacing *The Devil made me do it* with *Entropy made me do it* seemed fitting. Also, since an increase in entropy is responsible for so much in the universe, the title made thermodynamic sense as well. Listing several devices that are analyzed using the Second Law and referring to them as Shenanigans seemed to fit the whole entropy-as-the-devil theme.
 - [Flame On, Torch!](../NotYetHere.qmd): The catch phrase of *Johnny Storm* of *The Fantastic Four* seemed the perfect clickbait for a video introduction to the chemistry of combustion reactions. 
 - [From Mole to Megawatt: The Full Journey Through Chemical and Thermal Engineering](../NotYetHere.qmd): We attempted to combine the overwhelming scope of the DOFPro videos with clickbait-style phrases and a touch of alliteration. HOw did we do? Let us know in the comments to the video.
 - [Fueling the Fire: The Shocking Truth About Combustion Reactions!](../NotYetHere.qmd): *The Shocking Truth* and *Fueling the Fire* are both popular clickbait phrases. Using them to introduce a video about the thermodynamics of combustion reactions seemed to be a natural.
 - [Germain Hess and the Enthalpy of Doom](../NotYetHere.qmd): A direct rip-off of *Indiana Jones and the Temple of Doom* applied to Hess's law and enthalpy of reaction calculations. We're still within fair-use guidelines.
 - [Gotta Keep ’Em Separated](../NotYetHere.qmd): A blatant rip-off of the first line from *The Offspring*'s 1994 song *Come Out and Play*. The video is all about doing calculations for chemical separators, so the title seemed relevant.
 - [How Deviant and Mean Are Your Data? Introduction and Basics, Part 1, Just the Facts](../NotYetHere.qmd): *Deviant* and *Mean* are both popular clickbait words. They also happen to be closely related to *Standard Deviation* and *Data Mean* which are the subjects of this set of videos. We couldn't squeeze in *Standard Error* or *Confidence Interval*, but we did try. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [How Deviant and Mean Are Your Data? Introduction and Basics, Part 1, The Full Story](../NotYetHere.qmd): *Deviant* and *Mean* are both popular clickbait words. They also happen to be closely related to *Standard Deviation* and *Data Mean* which are the subjects of this set of videos. We couldn't squeeze in *Standard Error* or *Confidence Interval*, but we did try. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [How Deviant and Mean Are Your Data? Introduction and Basics, Part 2, Just the Facts](../NotYetHere.qmd): *Deviant* and *Mean* are both popular clickbait words. They also happen to be closely related to *Standard Deviation* and *Data Mean* which are the subjects of this set of videos. We couldn't squeeze in *Standard Error* or *Confidence Interval*, but we did try. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [How Deviant and Mean Are Your Data? Introduction and Basics, Part 2, The Full Story](../NotYetHere.qmd): *Deviant* and *Mean* are both popular clickbait words. They also happen to be closely related to *Standard Deviation* and *Data Mean* which are the subjects of this set of videos. We couldn't squeeze in *Standard Error* or *Confidence Interval*, but we did try. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [How Did You Think I Would React?](../NotYetHere.qmd): *How Did You Think I Would React?* is a popular RomCom and Sitcom phrase. We hoped that it would be clickbaitish enough to attract people to a video introducing the three classical chemical kinetic reactors, the batch, the CSTR, and the PFR.
 - [How Keen Is Your Rank? Just the Facts](../NotYetHere.qmd): In our interviews about temperature scales, most everyone knew the Celsius scale, the Kelvin scale, and the Fahrenheit scale, but no-one knew or remembered the Rankine scale. They weren't too *keen* on it. A pun on *Rankine* as *Rank* and *Keen* seemed the perfect way to introduce the video. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [How Keen Is Your Rank? The Full Story](../NotYetHere.qmd): In our interviews about temperature scales, most everyone knew the Celsius scale, the Kelvin scale, and the Fahrenheit scale, but no-one knew or remembered the Rankine scale. They weren't too *keen* on it. A pun on *Rankine* as *Rank* and *Keen* seemed the perfect way to introduce the video. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [How Much Entropy Can You Balance on the Head of a Pin (or in an Open Steady-State System)?](../NotYetHere.qmd): Somehow the Second Law of Thermodynamics always makes us think of 17th-century Protestant theologians and philosophers. We changed the question from "how many angels can stand on the head of a pin?" to *How Much Entropy Can You Balance on the Head of a Pin?* and then added the bit about open steady-state systems to give a clue as to the actual subject of the video. We may be a little obscure, but at least some of you got the reference.
 - [How to Have a Quickie with Your Data, Part 1](../NotYetHere.qmd): The similarity with *How to have a quickie with your date* is pure coincidence and didn't even occur to us until someone pointed it out to us after the video was recorded and it was too late to change the title. It was *supposed* to explain how you could quickly and efficiently do data analysis on your experimental data. We apologize for letting this one slip in here.
 - [How to Have a Quickie with Your Data, Part 2](../NotYetHere.qmd): The similarity with *How to have a quickie with your date* is pure coincidence and didn't even occur to us until someone pointed it out to us after the video was recorded and it was too late to change the title. It was *supposed* to explain how you could quickly and efficiently do data analysis on your experimental data. We apologize for letting this one slip in here.
 - [How to Keep Your Balance](../NotYetHere.qmd): The general balance equation is the basis for mass balance, mole balances, energy balances, entropy balances, and exergy balances. We were hunting for a clickbait-type title and *How to keep your balance* seemed appropriate.
 - [Ideal Gases EXPOSED: Are They Even Real?!!](../NotYetHere.qmd): *EXPOSED* is one of the most frequently use clickbait words. Since the next videos were about real-gas calculations, asking if ideal gases were real was perfect from both a clickbait and engineering point of view.
 - [Interpol Is Late to a Mind-Blowing Math Hack, Just the Facts](../NotYetHere.qmd): *Mind-blowing math hack* is the most use math-related clickbait phrase. There isn't much you can do with *interpolate*, the subject of the video. We decided to go with the [malapropism](https://en.wikipedia.org/wiki/Malapropism) route. *Interpol* is a good name to generate interest (what **are** those international criminals doing). And Interopol being late sounds like a scandal. It seemed like the perfect combination. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [Interpol Is Late to a Mind-Blowing Math Hack, The Full Story](../NotYetHere.qmd): *Mind-blowing math hack* is the most use math-related clickbait phrase. There isn't much you can do with *interpolate*, the subject of the video. We decided to go with the [malapropism}(https://en.wikipedia.org/wiki/Malapropism) route. *Interpol* is a good name to generate interest (what **are** those international criminals doing). And Interpol being late sounds like a scandal. It seemed like the perfect combination. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [Is Furlongs Per Fortnight a Thing?](../NotYetHere.qmd): We decided to violate [Betteridge's Law of Headlines](https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines) and show in the video that [furlongs per fortnight](https://en.wikipedia.org/wiki/FFF_system) is *indeed* a thing. The phrase is used to mock the silly way engineers (especially American engineers) have to do unit conversions, and the video explains just how to do it (convert units, not mock engineers).
 - [Is It Hot in Here, or Just My Thermistor?](../NotYetHere.qmd): The famous stand-up comedian line is, "Is it hot in here, or is it just me?". It's usually done as ironic self-praise, but is occasionally used sincerely as a pick-up line. We do not condone its use, however. Changing the phrase slightly into a title to a video about temperature sensors seemed to have the right sense of humor with a slight [double-entendre](https://en.wikipedia.org/wiki/Double_entendre) vibe.
 - [Is Your Process Data Spread Smooth or Chunky? Just the Facts](../NotYetHere.qmd): There are a number of processed spreads on the market such as processed cheese spread, processed peanut spread a.k.a peanut butter, chocolate hazelnut spreads, and other nut spreads. This video is an introduction to process data. The similarity to processed nut spreads seemed like a pun that was just too good to pass up. Since you can smooth data, and chunky data are a thing in control charts, the question *could* be serious, but it's not. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [Is Your Process Data Spread Smooth or Chunky? The Full Story](../NotYetHere.qmd): There are a number of processed spreads on the markets uch as processed cheese spread, processed peanut spread a.k.a peanut butter, chocolate hazelnut spreads, and other nut spreads. This video is an introduction to process data. The similarity to processed nut spreads seemed like a pun that was just too good to pass up. Since you can smooth data, and chunky data are a thing in control charts, the question *could* be serious, but it's not. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [It’s Totally Tubular, Man!](../NotYetHere.qmd): The other common name for a Plug-Flow Reactor (PFR) is a *Tubular Reactor*. Since the video presents a sample calculation appled to PFR's, CSTR's and batch reactors, and starts with a PFR, the video is only *partially* tubular, bu this '80s surfer phrase is still occassionally used.
 - [Just Try to Break This Law! I Dare You!](../NotYetHere.qmd): On a macroscopic scale for non-relativistic systems, the FIrst Law of Thermodynamics is one of those physical laws that is considered inviolate. Both *I dare you* and *Just try to* are popular clickbait phrases. The title seemed to fit a video introducing the First Law.
 - [Leaving Radiator Springs In the Dust](../NotYetHere.qmd): This video explores *bypass* and *recycle* as used in chemical processes. One of the most well-known bypasses in pop culture is when the Interstate bypasses *Radiator Springs* in the Pixar film *Cars*. Referencing a famous bypass as the title to a video about bypass was an opportunity too good to pass up.
 - [Linear Regression in R](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to do linear regression calculations with the statistics language *R*. If you have a good or amusing alternate title, put it in the comments.
 - [Modeling the Rankine Cycle in DWSIM](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to model a Rankine cycle with the open-source chemical process simulator, DWSIM. If you have a good or amusing alternate title, put it in the comments.
 - [Modeling the Vapor Compression Cycle in DWSIM](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to model a vapor compression cycle with the open-source chemical process simulator, DWSIM. If you have a good or amusing alternate title, put it in the comments.
 - [No Clear Interpretation, a Mind-Blowing Math Hack](../NotYetHere.qmd): *Mind-blowing math hack* is the most use math-related clickbait phrase. There isn't much you can do with *nonlinear interpolation*, the subject of the video. We decided to go with the [malapropism](https://en.wikipedia.org/wiki/Malapropism) route. *No clear* for *nonlinear* and *interpretation* for *interpolation* seemed like good malapropisms. Together, they convey there is no easy way to understand the subject, which is a good clickbait trick. It seemed like the perfect combination.
 - [Oh, Henry!](../NotYetHere.qmd): The video discusses, among other things, the dissolution of gases into a liquid, which is described by Henry's law. There was a famous candy bar (still is in Canada) named [On Henry!](https://en.wikipedia.org/wiki/Oh_Henry!) which may have been named after the author [O. Henry](https://en.wikipedia.org/wiki/O._Henry). It was hard to pass up on over a hundred years of free publicity.
 - [React But Maintain Your Equilibrium, Part 1](../NotYetHere.qmd): The subject matter of the video is chemical reaction equilibrium or equilibrium reactors. The word *React* has a certain amount of clickbait value and *maintain your equilibrium* is a popular self-hep phrase. Combining the two seemed like a natural fit for getting clicks.
 - [React But Maintain Your Equilibrium, Part 2](../NotYetHere.qmd): The subject matter of the video is chemical reaction equilibrium or equilibrium reactors. The word *React* has a certain amount of clickbait value and *maintain your equilibrium* is a popular self-hep phrase. Combining the two seemed like a natural fit for getting clicks.
 - [React Hard: The First Law Gets Chemical](../NotYetHere.qmd): The first part is a blatant rip-off of the movie title *Die Hard*. We're still within fair-use guidelines, however*. *The First Law Gets Chemical* is a spin on the movie hero getting physical. The video is the first part of a two-parter on the First Law applied to chemically reacting systems.
 - [React Harder: Formation Heats and Alternate Endings](../NotYetHere.qmd): The first part is a blatant rip-off of the movie sequel title *Die Harder*. We're still within fair-use guidelines, however*. *Formation Heats and Alternate Endings* conjures up images of heated action and movie alternate endings. The video is the second part of a two-parter on the First Law applied to chemically reacting systems. It looks at alternate calculation strategies.
 - [REAL Gas Mixtures EXPLAINED Don’t Let This Cost You Points on Your Exam! Part 1](../NotYetHere.qmd): *EXPLAINED* is a popular clickbait word. *Don’t Let This Cost You Points on Your Exam!* is a direct appeal to students and is popular clickbait as well.
 - [REAL Gas Mixtures EXPLAINED Don’t Let This Cost You Points on Your Exam! Part 2](../NotYetHere.qmd): *EXPLAINED* is a popular clickbait word. *Don’t Let This Cost You Points on Your Exam!* is a direct appeal to students and is popular clickbait as well.
 - [Recycling Before Recycling Was Cool](../NotYetHere.qmd): Chemical Engineers were the first to make extensive use of recycle in Engineering to increase the efficiency of a process. It was done long before the concept of recycling entered popular culture. *X before X was cool* is a common phrase for gently denigrationg those late to a social trend.
 - [Reference Not Found: Mixing, Dissolving, and Changing the Rules](../NotYetHere.qmd): This video describes having different reference states for different property tables, enthalpy of solution calculations, and enthalpy of mixing calculations. Because of the change of reference, having hte classic 404 Reference Not Fount or Link Not Found seemed like a reasonable clickbait. The mixing and dissolving should be obvious. The changing the rules again refers back to different reference states.
 - [Resistance is Futile. Entropy always wins](../NotYetHere.qmd): The classic [Borg](https://en.wikipedia.org/wiki/Borg) line, "Resistance is futile" seemed appropriate when dealing with the Second Law of Thermodynamics, since you can slow down the entropy increase, but you can never stop it. *Entropy always wins* is the same sentiment expressed in different terms. Engineers tend to be fans of Star Trek, Star Wars, and Harry Potter, so references to any of those franchises tend to be popular.
 - [Revenge of the Fridge: Vapor Compression Strikes Back](../NotYetHere.qmd): Blatant rip-offs of two *Star Wars* titles:  *Revenge of the Sith* and *The Empire Strikes Back*. We're still within fair-use guidelines. The video discusses the vapor compression refrigeration cycle and refrigeration in general, so the combination seemed to work.
 - [Sadi Carnot and the Power of Fire, the 1824 Edition Part 1](../NotYetHere.qmd): A not-so blatant rip-off of the title, *Harry Potter and the Goblet of Fire*. Sadi Carnot published an essay in June 1824 entitled *Reflections on the Motive Power of Fire*, which is the basis of the Carnot engine. That's the reason for the 1824 edition, plus it makes it sound like it has more gravitas. The Harry Potter films split the final book because of length. We did the same thing here.
 - [Sadi Carnot and the Power of Fire, the 1824 Edition Part 2](../NotYetHere.qmd): A not-so blatant rip-off of the title, *Harry Potter and the Goblet of Fire*. Sadi Carnot published an essay in June 1824 entitled *Reflections on the Motive Power of Fire*, which is the basis of the Carnot engine. That's the reason for the 1824 edition, plus it makes it sound like it has more gravitas. The Harry Potter films split the final book because of length. We did the same thing here.
 - [Show Some Flash and Dew the Dew with a Little Bubbly!](../NotYetHere.qmd): This video is a graphical explanation of Bubble, Dew, and Flash calculations. It comes before [Dew Your Bubbles Have Flash?](../NotYetHere.qmd), and like that title, this title combines the *Do the dew* spelling of *do* with the clickbait-rich words *bubbles* and *flash*.
 - [Solving Nonlinear Equations with Spreadsheets](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to solve nonlinear equations numerically with a spreadsheet. If you have a good or amusing alternate title, put it in the comments.
 - [Speed Balancing](../NotYetHere.qmd): This video is the companion video to [How to Keep Your Balance](../NotYetHere.qmd) and expalins ways to speed up your balance calculations. *Speed X* where *X* is something like dating, eating, reading, or programming is a popular clickbait technique. Non-technical viewers will think first about doing physical balane exercises, and engineers will appreciate the pun.
 - [Steam: Get the Quality Right AFTER You Table It! Part 1](../NotYetHere.qmd): The video is about how to read and do calculations with steam tables, which, truth be told, is a dying art. *Get X right* where *X* is something like your calculations, your stretches, or your videos is a popular clickbait phrase. *Quality* is the fraction of steam in a steam/water mixture, but to the non-technical viewer it will remind them of Samwise Gamgee's quote to Faramir: "You took the chance, sir. Yes, sir, and showed your quality: the very highest." 
 - [Steam: Get the Quality Right AFTER You Table It! Part 2](../NotYetHere.qmd): The video is about how to read and do calculations with steam tables, which, truth be told, is a dying art. *Get X right* where *X* is something like your calculations, your stretches, or your videos is a popular clickbait phrase. *Quality* is the fraction of steam in a steam/water mixture, but to the non-technical viewer it will remind them of Samwise Gamgee's quote to Faramir: "You took the chance, sir. Yes, sir, and showed your quality: the very highest."
 - [The Enthalpy Games: Sunrise on the Calculations](../NotYetHere.qmd): A blatant rip-off of *The Hunger Games: Sunrise on the Reaping*. We're still within the guidelines for fair use, however. This video does example enthalpy calculations based on the equations derived in [The Enthalpy Games: The Ballad of Integrals and Means](../NotYetHere.qmd).
 - [The Enthalpy Games: The Ballad of Integrals and Means](../NotYetHere.qmd): A blatant rip-off of *The Hunger Games: The Ballade of Songbirds and Snakes*. We're still within the guidelines for fair use, however. This video develops the integrals for computing enthalpy changes and mean heat capacities from heat capacity equations in the Shomate form. The next video [The Enthalpy Games: Sunrise on the Calculations](../NotYetHere.qmd) does example calculations based on the equations derived in this video.
 - [The Isochronicles: This First Law Saga Is a Gas](../NotYetHere.qmd): This video develops the equations for isothermal, isobaric, isochoric, and isentropic processes for ideal gases. Since we're chronicling the different iso steps, The *Isochronicles* seemed like a perfect title.- [The Isochronicles: This First Law Saga Is a Gas](../NotYetHere.qmd): This video develops the equations for isothermal, isobaric, isochoric, and isentropic processes for ideal gases from the First Law of Thermodynamics, so *This First Law Saga Is a Gas* is a pun on ideal gases and *a gas* being slang for fun. Since we're chronicling the different iso steps, *The Isochronicles* seemed like a perfect title. It calls to mind such titles as *The Martian Chronicles*, *The Spiderwick Chronicles*, and *The Chronicles of Narnia*.
 - [The Law is a Thief: It Destroys Exergy and Laughs in Your Face Part 1](../NotYetHere.qmd): *The Law Is a Thief* taps into several prejudices about corrupt law enforcement. Having the law destroy something that you've never heard of and then mocking you is just such an emotional ride that few people could resist finding out more about it. The two-part video discusses the combined First and Second Laws of THermodynamics, which is useful for seeing where in your process you are wasting the most available energy and giving you leads as to where to increase efficiency.
 - [The Law is a Thief: It Destroys Exergy and Laughs in Your Face Part 2](../NotYetHere.qmd): *The Law Is a Thief* taps into several prejudices about corrupt law enforcement. Having the law destroy something that you've never heard of and then mocking you is just such an emotional ride that few people could resist finding out more about it. The two-part video discusses the combined First and Second Laws of THermodynamics, which is useful for seeing where in your process you are wasting the most available energy and giving you leads as to where to increase efficiency.
 - [The Most Annoying Equation Conversion](../NotYetHere.qmd): Most students who learn to convert an equation with dimensions, as opposed to converting a quantity wit dimensions, from one set of units to another find it really annoying. However, it is a really valuable skill when you need it. *Most annoying* is a good clickbait phrase, and the title acknowledges the frustration you are likely to feel while learning the method.
 - [The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 1](../NotYetHere.qmd): Both *The Shocking Truth* and *Are You Doing It Wrong?* and frequently used clickbait phrases. The three-part video describes the mole-balance math behind equilibrium separation stages, and then does examples. It's really easy to get confused about these equations and solve the problems incorrectly. The videos are trying to set you up for success. The first video derives the math.
 - [The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 2](../NotYetHere.qmd): Both *The Shocking Truth* and *Are You Doing It Wrong?* and frequently used clickbait phrases. The three-part video describes the mole-balance math behind equilibrium separation stages, and then does examples. It's really easy to get confused about these equations and solve the problems incorrectly. The videos are trying to set you up for success. The second video does two examples. The first example uses a binary phase diagram to solve the mole balances in an equilibrium stage in a distillation column. The second example uses Raoult's law to solve a ternary system in an equilibrium stage in a distillation column.
 - [The Shocking Truth About Equilibrium Stages—Are You Doing It Wrong? Part 3](../NotYetHere.qmd): Both *The Shocking Truth* and *Are You Doing It Wrong?* and frequently used clickbait phrases. The three-part video describes the mole-balance math behind equilibrium separation stages, and then does examples. It's really easy to get confused about these equations and solve the problems incorrectly. The videos are trying to set you up for success. The third video uses a ternary phase diagram to solve the mole balances in an equilibrium stage in a liquid-liquid extractor.
 - [The Symbolic Meaning of Recycling](../NotYetHere.qmd): *Symbolic meanings* are often used as clickbait for esoteric or hidden-knowledge sorts of videos. Recycling is still big with the save-the-planet crowd. Combining the two should be clickbait gold. The video derives the equations for a recycle loop and deliberately leaves them in symbolic form so the viewer can see mathematically what is going on. A slightly more accurate title would be *A Symbolic Derviation of the Mole Balances Around a Recycle Loop*. You can see why we chose the title we did.
 - [The Unauthorized Guide to Using Spreadsheets in Chemical Engineering](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This is the only one that doesn't. We've found that learning how to solve chemical and thermal process problem with spreadsheets is such a valuable skill, that we had to do something to increase viewership. *Unauthorized* is a very powerful clickbait word. We have no clue who would authorize the guide or would insist on only an authorized guide to learning spreadsheets, but hopefully the clickbait works. Let us know if it did in the comments.
 - [The ΔS-sentials of Calculating Entropy Changes](../NotYetHere.qmd): The symbol for an entropy change is *∆S*. The pun of using it as part of essentials when calculating entropy changes was too good to pass up.
 - [Under Pressure, Part 1, Just the Facts](../NotYetHere.qmd): *Under Pressure* was originally recorded by Queen and David Bowie. It's been covered by everyone from The Used and My Chemical Romance to Xiu Xiu and Michael Gira. How can you pass up more than 40 years of publicity? The actual two-part video covers how pressure is calculated and how it is used in chemical and thermal processes. It is the second most used easurement after temperature. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [Under Pressure, Part 1, The Full Story](../NotYetHere.qmd): *Under Pressure* was originally recorded by Queen and David Bowie. It's been covered by everyone from The Used and My Chemical Romance to Xiu Xiu and Michael Gira. How can you pass up more than 40 years of publicity? The actual two-part video covers how pressure is calculated and how it is used in chemical and thermal processes. It is the second most used easurement after temperature.  The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [Under Pressure, Part 2, Just the Facts](../NotYetHere.qmd): *Under Pressure* was originally recorded by Queen and David Bowie. It's been covered by everyone from The Used and My Chemical Romance to Xiu Xiu and Michael Gira. How can you pass up more than 40 years of publicity? The actual two-part video covers how pressure is calculated and how it is used in chemical and thermal processes. It is the second most used easurement after temperature.  The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [Under Pressure, Part 2, The Full Story](../NotYetHere.qmd): *Under Pressure* was originally recorded by Queen and David Bowie. It's been covered by everyone from The Used and My Chemical Romance to Xiu Xiu and Michael Gira. How can you pass up more than 40 years of publicity? The actual two-part video covers how pressure is calculated and how it is used in chemical and thermal processes. It is the second most used easurement after temperature.  The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [Using DWSIM to Create Binary Phase Diagrams](../NotYetHere.qmd): Most of the *How-To* videos that demonstrate using software have straightforward titles that describe what the are or what they do. This video describes how to create binary phase diagrams with DWSIM. If you have a good or amusing alternate title, put it in the comments.
 - [What Is a Mole? Just the Facts](../NotYetHere.qmd): This was the first video that we actually recorded and edited to work out the kinks in the process. Outside of chemistry and chemical engineering, very few people are familiar with moles as a unit of chemical measure. They think mainly of small burrowing creatures or double agents. If you watch closely, you may see *Mollage* who is a stuffed fabric mole originally created for an AP Chemistry class. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [What Is a Mole? The Full Story](../NotYetHere.qmd): This was the first video that we actually recorded and edited to work out the kinks in the process. Outside of chemistry and chemical engineering, very few people are familiar with moles as a unit of chemical measure. They think mainly of small burrowing creatures or double agents. If you watch closely, you may see *Mollage* who is a stuffed fabric mole originally created for an AP Chemistry class. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [What the Frac! Just the Facts](../NotYetHere.qmd): The video explains what mole fractions and mass fractions are and how to convert from one to the other. The title is a euphemistic malapropism for what in the military is known as *Whisky Tango Foxtrot*. The *Just the Facts* videos don't have interviews and have nice clean magic-screen graphics instead of hand-written dry-erase markers on a whiteboard.
 - [What the Frac! The Full Story](../NotYetHere.qmd): The video explains what mole fractions and mass fractions are and how to convert from one to the other. The title is a euphemistic malapropism for what in the military is known as *Whisky Tango Foxtrot*. The *The Full Story* videos have interviews and have hand-written dry-erase markers on a whiteboard instead of nice clean magic-screen graphics.
 - [What the Schmidt? Examples](../NotYetHere.qmd): The video discusses a number of dimensionless groups or dimensionless numbers, one of which is the *Schmidt number*. The title is a euphemistic malapropism for an anglo-saxon epithet. 
 - [When Getting Gassed Isn’t Ideal, Part 1](../NotYetHere.qmd): This pair of videos are a follow-on to [Ideal Gases EXPOSED: Are They Even Real?!!](../NotYetHere.qmd). Getting gassed is a euphemism for becoming intoxicated, especially on inhalants. The videos discuss doing real gas calculations with the pressure and temperature range is outside the ideal gas range, so the title is a pun on using inhalants at the wrong time and doing real-gas calculations.
 - [When Getting Gassed Isn’t Ideal, Part 2](../NotYetHere.qmd): Getting gassed is a euphemism for becoming intoxicated, especially on inhalants. The videos discuss doing real gas calculations with the pressure and temperature range is outside the ideal gas range, so the title is a pun on using inhalants at the wrong time and doing real-gas calculations.
 - [When You Saw It, What Was the Extent of Your Reaction? Part 1](../NotYetHere.qmd): This three-part video set explores modeling chemical reactors using the *extent of reaction*, a parameter that depends on either chemical equilibrium or chemical kinetics, but not explicitly. It is treated in the videos as a specified or calclated parameter. The title is a common phrase in RomComs or dramatic productions when a character see something heartbreaking and is interrogated by a friend. The title is therefore a pun between the extent of a chemical reaction and the extent of an emotional reaction. See, we told you they weren't funny if you have to ahve them explained to you.
 - [When You Saw It, What Was the Extent of Your Reaction? Part 2](../NotYetHere.qmd): This three-part video set explores modeling chemical reactors using the *extent of reaction*, a parameter that depends on either chemical equilibrium or chemical kinetics, but not explicitly. It is treated in the videos as a specified or calclated parameter. The title is a common phrase in RomComs or dramatic productions when a character see something heartbreaking and is interrogated by a friend. The title is therefore a pun between the extent of a chemical reaction and the extent of an emotional reaction. See, we told you they weren't funny if you have to ahve them explained to you.
 - [When You Saw It, What Was the Extent of Your Reaction? Part 3](../NotYetHere.qmd): This three-part video set explores modeling chemical reactors using the *extent of reaction*, a parameter that depends on either chemical equilibrium or chemical kinetics, but not explicitly. It is treated in the videos as a specified or calclated parameter. The title is a common phrase in RomComs or dramatic productions when a character see something heartbreaking and is interrogated by a friend. The title is therefore a pun between the extent of a chemical reaction and the extent of an emotional reaction. See, we told you they weren't funny if you have to ahve them explained to you.
 - [Where Does Sherwood Hide His Unit?](../NotYetHere.qmd): The video discusses a number of dimensionless groups or dimensionless numbers, one of which is the *Sherwood number*, but Professor Sherwood always referred to it as the *Mass-Transfer Nusselt Number*. The individual values in a dimensionless group all have units, but the overall group is unitless. The title is therefore a double entendre. 
 - [Wishing Upon a CSTR](../NotYetHere.qmd): A well mixed reactor is also known as a continuously stirred tank reactor or by the acronym CSTR, pronounced Sea-Star. Wishing upon a star is a popular superstition in most of the world, so wishing upon a CSTR should have a lot of aappeal. This video is a companion video to [It’s Totally Tubular, Man!](../NotYetHere.qmd) and [How Did You Think I Would React?](../NotYetHere.qmd).