---
title: "Equilibrium Reactors Reference Page<br/>*React But Maintain Your Equilibrium*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---

{{< include /LinkKey.qmd >}}

# Intro to *React But Maintain Your Equilibrium*

In many reactions the reaction rate is fast compared to the residence time of the reactor. When this occurs, the reactor outlet composition is determined not by reaction kinetics but by **chemical equilibrium**.

Equilibrium reactor calculations combine **material balances**, **stoichiometry**, and **equilibrium relationships** to determine the final composition of the reaction mixture. These videos introduce equilibrium reactors and demonstrate how to solve typical equilibrium reactor problems.

---

## React But Maintain Your Equilibrium Part 1

This video introduces the concept of equilibrium reactors and explains how equilibrium constants are used to determine the composition of a reaction mixture.

<iframe width="560" height="315" src="https://www.youtube.com/embed/0GS8XEHRBMk?si=anu1Kj9RFzDi7XGU" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](54-EquilReact1Visuals.qmd)

---

## React But Maintain Your Equilibrium Part 2

This video works through a complete equilibrium reactor example, showing how material balances and equilibrium relationships are combined to determine the outlet composition.

<iframe width="560" height="315" src="https://www.youtube.com/embed/GI8tuSRrIcc?si=jQmusfP4c38elk4j" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](55-EquilReact2Visuals.qmd)

---

# Examples and Definitions

## Examples Links

- [Equilibrium Reactor Example](https://dofprobucket1.s3.us-east-2.amazonaws.com/material/EquilibriumReactionExample.ods) – The spreadsheet from Part 2

---

## Definitions

Equilibrium Reactor  
: A reactor in which the reaction proceeds until chemical equilibrium is reached. The outlet composition is determined by the **equilibrium constant** and the inlet composition.

Equilibrium reactors are often used when reactions are **fast compared to the residence time of the reactor**, so the reaction effectively reaches equilibrium before the material exits the reactor.

[Equilibrium Constant](https://en.wikipedia.org/wiki/Equilibrium_constant), $K$
: A dimensionless quantity that describes the equilibrium state of a chemical reaction. It is defined as the ratio of the activities (often approximated by concentrations or partial pressures) of the products to the reactants, each raised to the power of their stoichiometric coefficients.

The equilibrium constant determines the **position of equilibrium** and therefore the maximum possible conversion under given conditions.

Equilibrium Conversion  
: The fractional conversion of a reactant when the reaction mixture has reached equilibrium. It represents the **maximum conversion achievable under the specified temperature and pressure conditions**.

Equilibrium conversion depends on the equilibrium constant and the initial composition of the reacting mixture.

---

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**Wishing Upon a CSTR**  
*Batch, CSTR, PFR*  
[Video](https://youtu.be/6tnVFq7dSbE), [Info Page](../../balances/material/KineticReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/47-BatchCSTRPFRIntroVisuals.qmd)

### Previous video

**It’s Totally Tubular, Man!**  
*CSTR, PFR, Batch Example*  
[Video](https://youtu.be/OAzXx9Kq2nU), [Info Page](../../balances/material/KineticReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/47.5-ReactorExamplesVisuals.qmd)

### Next video

**Flame On, Torch!**  
*Combustion reactions*  
[Video](https://youtu.be/G2sKW_6N2BA), [Info Page](../../balances/material/CombustionReactionsVideoInfoWebPage.qmd), [Visuals](../../balances/material/59-CombRxnsPart1Visuals.qmd)

### Two videos forward

**A Combustible Mixture!**  
*Sample combustion reactions*  
[Video](https://youtu.be/hvIk-evMp88), [Info Page](../../balances/material/CombustionReactionsVideoInfoWebPage.qmd), [Visuals](../../balances/material/60-CombRxnsPart2Visuals.qmd)