---
title: "Fractional-Conversion and Extent-of-Reaction Reactors Reference Page<br/>*When You Saw It, What Was the Extent of Your Reaction?*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
::: {.callout-important title="Still Under Construction!"}
This web page is just a bare outline. The complete details have not been filled in yet.
:::
# Intro to *When You Saw It, What Was the Extent of Your Reaction?*

Main title explanation

## Part 1

Video 1 explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/HKYYp5UxwpA?si=JglGKTWhKhMGefy2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](41-UnitOpsReactPart1Visuals.qmd)

## Part 2

Video  explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/XmLXR_KOZMk?si=TpAOboYR3Is11NBg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](42-UnitOpsReactPart2Visuals.qmd)

## Part 3

Video  explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/PPi-ka3iRvI?si=vu4qzloJBAQz4LzO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](42.5-UnitOpsReactPart3Visuals.qmd)

# Examples and Definitions

## Examples Links

## Definitions

Chemical Reaction
: A process in which one or more substances (reactants) are transformed into one or more different substances (products) through the breaking and forming of chemical bonds. Chemical reactions involve the rearrangement of atoms and can be classified into various types, such as synthesis, decomposition, single replacement, and double replacement reactions. The progress of a chemical reaction can be quantified using parameters like extent of reaction, fractional conversion, yield, and selectivity.

[Stoichiometric Coefficients](https://en.wikipedia.org/wiki/Stoichiometry), $\nu_i$
: The numerical values that represent the relative amounts of reactants and products in a balanced chemical equation. Stoichiometric coefficients indicate the proportion of each substance involved in the reaction and are used to calculate the extent of reaction, fractional conversion, yield, and selectivity. For example, in the reaction $\mathrm{A + 2B \rightarrow C}$, the stoichiometric coefficients are negative 1 for $\mathrm{A}$, negative 2 for $\mathrm{B}$, and 1 for $\mathrm{C}$.

[Extent of Reaction](https://en.wikipedia.org/wiki/Extent_of_reaction), $\xi$, $\dot{\xi}$
: A measure of the progress of a chemical reaction, defined as the ratio of the amount of reactant that has been converted to product to the total amount of reactant initially present. It is often denoted by the symbol $\xi$ (xi) and can be used to determine the composition of the reaction mixture at any given time.

Fractional Conversion, $f$
: The fraction of the initial amount of a reactant that has been converted to product in a chemical reaction. It is calculated as the amount of reactant converted divided by the initial amount of reactant, and is often denoted by the symbol $f$. Fractional conversion is a key parameter in chemical reaction engineering, as it helps to determine the efficiency of a reaction and the design of reactors.

Yield, $Y$
: The amount of product obtained from a chemical reaction relative to the theoretical maximum amount that could be produced based on the initial amount of reactant. Yield is often expressed as a percentage and is calculated as the actual amount of product obtained divided by the theoretical maximum amount, multiplied by 100. Yield is an important metric in chemical engineering, as it indicates the efficiency of a reaction and can be used to optimize reaction conditions and reactor design.

Selectivity
: A measure of the preference of a chemical reaction to produce a specific product over other possible products. Selectivity is calculated as the amount of desired product formed divided by the total amount of all products formed, and is often expressed as a percentage. High selectivity indicates that the reaction favors the formation of the desired product, while low selectivity indicates that the reaction produces a significant amount of undesired products. Selectivity is a critical parameter in chemical reaction engineering, as it can impact the overall efficiency and economic viability of a chemical process.

Differential Balance
: A mathematical expression that describes the rate of change of a quantity (such as mass, energy, or moles) in a system as a function of time. Differential balances are used to model the behavior of chemical reactors and other processes, and are typically expressed as ordinary differential equations (ODEs) or partial differential equations (PDEs). Solving these equations allows engineers to predict the performance of a reactor and optimize its design and operation.

Integral Balance
: A mathematical expression that describes the total change of a quantity (such as mass, energy, or moles) in a system over a specified time interval. Integral balances are derived from differential balances by integrating the rate of change over time, and are often used to analyze the overall performance of a chemical reactor or process. Integral balances can provide insights into the cumulative effects of a reaction or process and are useful for determining the total amount of product formed, the total energy consumed, or the total mass transferred during a reaction or process.

[Composition](https://en.wikipedia.org/wiki/Chemical_composition#Composite_mixture) or [Mole Fraction](https://en.wikipedia.org/wiki/Mole_fraction)
: The ratio of the amount of a specific component in a mixture to the total amount of all components in the mixture. Mole fraction is a dimensionless quantity that is often used to describe the composition of a reaction mixture or a solution, and is calculated as the number of moles of the component of interest divided by the total number of moles of all components in the mixture. Mole fraction is an important parameter in chemical engineering, as it can impact the rate of reaction, the equilibrium position, and the properties of the reaction mixture.


# Other Links and Videos

## Other Links

## Previous and Following Videos

### The video previous to the previous video (i.e., two videos back)

**Speed Balancing**<br/>*General Balance Equation Definitions and Suggestions*<br/>[Video](https://youtu.be/Pmp2IxgL9FM), [Info Page](../../balances/general/index.qmd), [Visuals](../../balances/general/SpeedBalancingJTFVisuals.qmd)

### The previous video (i.e., one video back)

**Gotta Keep ‘Em Separated**<br/>*Mixer, Divider, and Separator mole balances*<br/>[Video](https://youtu.be/pRg1m0_9Psg), [Info Page](../../balances/material/MixDivideSeparateVideoInfoWebPage.qmd), [Visuals](../../balances/material/40-UnitOpsMixDivSepVisuals.qmd)

### The next video (i.e., one video forward)

**Recycling Before Recycling Was Cool**<br/>*Basics of recycle*<br/>[Video](https://youtu.be/R7tIQyBUWn8), [Info Page](../../balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](../../balances/material/43-RecycleBypassPartVisuals.qmd)

### The next after next video (i.e. two videos forward)

**Leaving Radiator Springs In the Dust**<br/>*Basics of bypass and a recycle example*<br/>[Video](https://youtu.be/tjzDu7_n-NI), [Info Page](../../balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](../../balances/material/44-RecycleBypassPart2Visuals.qmd)
