---
title: "Henry's Law Reference Page<br/>*Oh, Henry!*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---

{{< include /LinkKey.qmd >}}

# Intro to Henry's Law

When a gas is in contact with a liquid, some of the gas may dissolve into the liquid phase. The amount that dissolves depends on the gas, the liquid, the temperature, and the pressure.

Henry’s Law describes the equilibrium relationship between the partial pressure of a gas above a liquid and the amount of that gas dissolved in the liquid. This principle is widely used in chemical engineering for problems involving humidification, gas absorption, and gas–liquid equilibrium.

---

## Oh, Henry!

This video introduces Henry’s Law and shows how it is applied to systems containing a single condensible vapor mixed with a noncondensible gas.

<iframe width="560" height="315" src="https://www.youtube.com/embed/dCOQy1C7yf0?si=TKD1qWmpW3LuX1__" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](73-Visuals.qmd)

---

# Examples and Definitions

## Examples Links

- [Henry's Law Example](https://dofprobucket1.s3.us-east-2.amazonaws.com/material/SingleComponentExamples.ods) – A spreadsheet with the sample calculations from the video

---

## Definitions

[Clapeyron Equation](https://en.wikipedia.org/wiki/Clausius%E2%80%93Clapeyron_relation#Exact_Clapeyron_equation)  
: A thermodynamic equation relating the slope of the vapor-pressure–temperature curve to the enthalpy of vaporization, the absolute temperature, and the molar volumes of the vapor and liquid phases.

$$
\frac{dp^*}{dT} = \frac{\Delta \hat{H}_{v}}{T(\hat{V}_{g} - \hat{V}_l)}
$$

[Clausius–Clapeyron Equation](https://en.wikipedia.org/wiki/Clausius%E2%80%93Clapeyron_relation)  
: An approximate equation relating the vapor pressure of a pure substance to temperature, assuming that the enthalpy of vaporization does not vary with temperature.

$$
\ln p^{*} = -\frac{\Delta \hat{H}_v}{RT} + B
$$

[Dew-Point Temperature](https://en.wikipedia.org/wiki/Dew_point)  
: The temperature at which a condensible vapor begins to condense from a gas–vapor mixture.

[Antoine Equation](https://en.wikipedia.org/wiki/Antoine_equation)  
: An empirical equation relating the vapor pressure of a pure substance to temperature.

$$
\log_{10} p^{*} = A - \frac{B}{T + C}
$$

Relative Saturation or [Relative Humidity](https://en.wikipedia.org/wiki/Humidity#Relative_humidity)  
: The ratio of the partial pressure of a condensible vapor to its vapor pressure at the same temperature.

$$
s_r \text{ or } h_r = \frac{p_i}{p_i^*(T)} \times 100\%
$$

Molal Saturation or Molal Humidity  
: The ratio of moles of vapor to moles of vapor-free (dry) gas.

$$
s_m \text{ or } h_m = \frac{p_i}{P - p_i}
$$

$$
= \frac{\text{moles of vapor}}{\text{moles of vapor-free (dry) gas}}
$$

Absolute Saturation or [Absolute Humidity](https://en.wikipedia.org/wiki/Humidity#Absolute_humidity)  
: The ratio of the mass of vapor to the mass of vapor-free (dry) gas.

$$
s_a \text{ or } h_a =
\frac{p_i M_i}{(P - p_i) M_{dry}}
$$

$$
= \frac{\text{mass of vapor}}{\text{mass of vapor-free (dry) gas}}
$$

Percentage Saturation or Percentage Humidity  
: The ratio of the molal saturation to the molal saturation at equilibrium.

$$
s_p \text{ or } h_p =
100\% \times \frac{s_m}{s_m^*}
$$

$$
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ = 100\% \times \frac{\frac{p_i}{P-p_i}}{\frac{p_i^*}{P-p_i^*}}
$$

---

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**Can You Tell an Azeotrope from a Peritectic? Get Your Phase Diagrams Right! Part 2**  
*Ternary Phase Diagrams, Lever Rule*  
[Video](https://youtu.be/QBREikNSvGI), [Info Page](../../balances/material/ReadingPhaseDiagramsVideoInfoWebPage.qmd), [Visuals](../../balances/material/71-IntroMultiphasePart2Visuals.qmd)

### Previous video

**Show Some Flash and Dew the Dew with a Little Bubbly!**  
*Graphical BUBL P, DEW P, BUBL T, DEW T, and FLASH calculations*  
[Video](https://youtu.be/shKvpcsJIEM), [Info Page](../../balances/material/GraphicalDewBubbleFlashVideoInfoWebPage.qmd), [Visuals](../../balances/material/72-BubbleDewFlashVisuals.qmd)

### Next video

**Dew Your Bubbles Have Flash? Part 1**  
*Raoult's law, BUBL P, DEW P*  
[Video](https://youtu.be/vSkSRi6HYVQ), [Info Page](../../balances/material/RaoultsLawDewBubbleFlashVideoInfoWebPage.qmd), [Visuals](../../balances/material/74-Visuals.qmd)

### Two videos forward

**Dew Your Bubbles Have Flash? Part 2**  
*BUBL T, DEW T*  
[Video](https://youtu.be/9GyrfJzg-tg), [Info Page](../../balances/material/RaoultsLawDewBubbleFlashVideoInfoWebPage.qmd), [Visuals](../../balances/material/75-Visuals.qmd)