---
title: "Kinetic Reactors Reference Page"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
::: {.callout-important title="Still Under Construction!"}
This web page is just a bare outline. The complete details have not been filled in yet.
:::
# Intro to Kinetic Reactors

Main title explanation

## How Did You Think I Would React?

Video 1 explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/_qxHszVZYGk?si=bArMc7GxKvM-ug4l" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](46-KineticsIntroJTFVisuals.qmd)

## Wishing Upon a CSTR

Video  explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/6tnVFq7dSbE?si=2MBUW71WCRQVQ-xS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](47-BatchCSTRPFRIntroVisuals.qmd)

## It’s Totally Tubular, Man!

Video  explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/OAzXx9Kq2nU?si=WIoyQN_CdEFKu7hh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](47.5-ReactorExamplesVisuals.qmd)

# Examples and Definitions

## Examples Links

- [CSTR and PFR Demo](https://dofprobucket1.s3.us-east-2.amazonaws.com/material/CSTRPFRDemo.ods) – A spreadsheet with the results from the reactor design exercise in the videos

## Definitions

[Chemical Reactor](https://en.wikipedia.org/wiki/Chemical_reactor)
: A vessel or system in which a chemical reaction takes place. Reactors are designed to provide the necessary conditions for the reaction to occur, such as temperature, pressure, and mixing. Common types of chemical reactors include batch reactors, continuous stirred-tank reactors (CSTRs), and plug flow reactors (PFRs).

[Batch Reactor](https://en.wikipedia.org/wiki/Batch_reactor)
: A type of chemical reactor in which the reactants are loaded into the reactor, the reaction takes place, and then the products are removed. Batch reactors are typically used for small-scale production or when the reaction requires precise control over time.

[Continuous Stirred-Tank Reactor (CSTR)](https://en.wikipedia.org/wiki/Continuous_stirred-tank_reactor)
: A type of chemical reactor in which the reactants are continuously fed into the reactor, and the products are continuously removed. The contents of the reactor are well mixed, resulting in uniform composition throughout the reactor. CSTRs are commonly used in large-scale industrial processes.

[Plug Flow Reactor (PFR)](https://en.wikipedia.org/wiki/Plug_flow_reactor_model)
: A type of chemical reactor in which the reactants flow through the reactor as a plug, with no mixing in the flow direction. The composition of the reactants changes along the length of the reactor, and the reaction occurs as the reactants move through the reactor. PFRs are often used in processes where a high conversion is desired, such as in the production of chemicals or in catalytic reactions.

[Space Time](https://en.wikipedia.org/wiki/Residence_time#Turnover_time)
: The time required for a given volume of reactants to pass through a reactor. It is calculated as the volume of the reactor divided by the volumetric flow rate of the feed. Space time is an important parameter in reactor design and analysis, as it helps determine the residence time of the reactants in the reactor and the extent of the reaction.

# Other Links and Videos

## Other Links

## Previous and Following Videos

### The video previous to the previous video (i.e., two videos back)

**Leaving Radiator Springs In the Dust**<br/>*Basics of bypass and a recycle example*<br/>[Video](https://youtu.be/tjzDu7_n-NI), [Info Page](../../balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](../../balances/material/44-RecycleBypassPart2Visuals.qmd)

### The previous video (i.e., one video back)

**The Symbolic Meaning of Recycling**<br/>*Analytic solution of a recycle PFD*<br/>[Video](https://youtu.be/CF18jpqZzgc), [Info Page](../../balances/material/RecyclingBypassVideoInfoWebPage.qmd), [Visuals](../../balances/material/45-RecycleSymbSolVisuals.qmd)

### The next video (i.e., one video forward)

**React But Maintain Your Equilibrium Part 1**<br/>*Basics of equilibrium reactors*<br/>[Video](https://youtu.be/0GS8XEHRBMk), [Info Page](../../balances/material/EquilibriumReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/54-EquilReact1Visuals.qmd)

### The next after next video (i.e. two videos forward)

**React But Maintain Your Equilibrium Part 2**<br/>*Equilibrium reactor example*<br/>[Video](https://youtu.be/GI8tuSRrIcc), [Info Page](../../balances/material/EquilibriumReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/55-EquilReact2Visuals.qmd)
