---
title: "*Gotta Keep ‘Em Separated* (Mixers, Dividers, Separators) Reference Page"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
::: {.callout-important title="Still Under Construction!"}
This web page is just a bare outline. The complete details have not been filled in yet.
:::
# Intro to *Gotta Keep ‘Em Separated*

Main title explanation

## Gotta Keep ‘Em Separated

Video 1 explanation

<iframe width="560" height="315" src="https://www.youtube.com/embed/pRg1m0_9Psg?si=ldy4MgqsU39JHH8p" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Visuals](../../NotYetHere.qmd)

# Definitions

Mixer

:   Mixes or combines multiple input streams into a single output stream. For each species the output stream has a flow equal to the sum of the flow of that species in each input stream. The output stream has a composition equal to the total flow of each species divided by the total flow of all species. Mixers can be as simple as a pipe tee or as complex as a stirred tank.

Divider

:   Divides the input stream into multiple output streams, each with the same composition as the input stream, but with differing flow rates.

Separator

:   Separates the input stream into multiple output streams, each with a different composition than the input stream. If the output streams have the same composition as the input stream, then the separator is a divider. The fraction of a given species in the input stream that exits in a given output stream is the split fraction for that species in that output stream.

Split Fraction

:   The fraction of a given species in the input stream that exits in a given output stream is the *split fraction* for that species in that output stream. For separators with two output streams, the split fractions for a given species in the two output streams sum to 1. For separators with more than two output streams, the split fractions for a given species in all output streams sum to 1.

Composition
:   Composition is the same as the mole or mass fraction of each species in a stream. See [*What the Frac?*](https://youtu.be/qJERzRm7xc0) for more details.

# Other Links and Videos

## Other Links

## Previous and Following Videos

### The video previous to the previous video (i.e., two videos back)

**How to Keep Your Balance**<br/>*System Definition and the General Balance Equation*<br/>[Video](https://youtu.be/-fjXc-Upxx4), [Info Page](../../balances/general/index.qmd), [Visuals](../../balances/general/KeepYourBalanceJTFVisuals.qmd)

### The previous video (i.e., one video back)

**Speed Balancing**<br/>*General Balance Equation Definitions and Suggestions*<br/>[Video](https://youtu.be/Pmp2IxgL9FM), [Info Page](../../balances/general/index.qmd), [Visuals](../../balances/general/SpeedBalancingJTFVisuals.qmd)

### The next video (i.e., one video forward)

**When You Saw It, What Was the Extent of Your Reaction? Part 1**<br/>*Chemical Reactor Single Reaction, $\xi$ and $f_{\mathrm{A}}$*<br/>[Video](https://youtu.be/HKYYp5UxwpA), [Info Page](../../balances/material/FractionalConversionReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/41-UnitOpsReactPart1Visuals.qmd)

### The next after next video (i.e. two videos forward)

**When You Saw It, What Was the Extent of Your Reaction? Part 2**<br/>*Chemical Reactor Multiple Reactions with Example, $\xi$ and $f_{\mathrm{A}}$*<br/>[Video](https://youtu.be/XmLXR_KOZMk), [Info Page](../../balances/material/FractionalConversionReactorsVideoInfoWebPage.qmd), [Visuals](../../balances/material/42-UnitOpsReactPart2Visuals.qmd)
