---
title: "Calculating Entropy Changes Reference Page<br/>*The  ∆S-sentials of Calculating Entropy Changes*"
author: "DOFPro group"
format: html
html-math-method: mathjax
---
{{< include /LinkKey.qmd >}}
# Intro to Calculating Entropy Changes

The Second Law introduces **entropy**, a thermodynamic property that allows us to determine the direction of spontaneous processes and evaluate the efficiency limits of real systems.

In many engineering problems, entropy changes must be calculated for systems such as **heat reservoirs, ideal gases, and substances described by thermodynamic property tables** (such as steam).

This page summarizes the common methods used to calculate entropy changes in these situations.

## The $\Delta S$-sentials of Calculating Entropy Changes 

This video explains how to calculate entropy changes for several important cases, including heat transfer with reservoirs, ideal-gas processes, and substances described using steam tables.

<iframe width="560" height="315" src="https://www.youtube.com/embed/z2e5Rq5r288?si=h073olXQ9GIgvabg" title="YouTube video player" frameborder="0" allowfullscreen></iframe>

[Visuals](115-CalcEntropyVisuals.qmd)

# Examples and Definitions

## Examples Links

## Definitions

Entropy Change  
: The change in entropy between two thermodynamic states.

$$
\Delta S = S_2 - S_1
$$

Entropy is a **state function**, meaning that the entropy change depends only on the initial and final states, not on the path taken between them.

Reversible Heat Transfer  
: Heat transfer that occurs through an infinitesimally small temperature difference. For a reversible process,

$$
dS = \frac{\delta Q_\mathrm{rev}}{T}
$$

Heat Reservoir Entropy Change  
: When heat $Q$ is transferred to or from an isothermal reservoir at temperature $T$,

$$
\Delta S = \frac{Q}{T}
$$

Ideal Gas Entropy Change  
: For an ideal gas undergoing a change of state,

$$
\Delta S = nC_p \ln\left(\frac{T_2}{T_1}\right) - nR\ln\left(\frac{P_2}{P_1}\right)
$$

or equivalently,

$$
\Delta S = nC_v \ln\left(\frac{T_2}{T_1}\right) + nR\ln\left(\frac{V_2}{V_1}\right)
$$

Steam Table Entropy  
: For substances such as water described using thermodynamic property tables, entropy values are tabulated. The entropy change is obtained directly from the tables:

$$
\Delta S = S_2 - S_1
$$

# Other Links and Videos

## Other Links

## Previous and Following Videos

### Two videos back

**React Harder: Formation Heats and Alternate Endings**  
*2 more Examples of the 1^st^ Law for Chemical Reactions*  
[Video](https://youtu.be/iqxJP6g-Qsc), [Info Page](../../balances/energy/Example1stLawForReactingSystemsVideoInfoWebPage.qmd), [Visuals](../../balances/energy/112-EnergeticsOfReactionsPt2Visuals.qmd)

### Previous video

**Resistance is Futile. Entropy Always Wins**  
*Intro to 2^nd^ Law*  
[Video](https://youtu.be/yqVUz1WA7M4), [Info Page](../../balances/entropy/IntroTo2ndLawVideoInfoWebPage.qmd), [Visuals](../../balances/entropy/113-Visuals.qmd)

### Next video

**Sadi Carnot and the Power of Fire, the 1824 Edition Part 1**  
*The Air-Standard Carnot Cycle*  
[Video](https://youtu.be/EDJQAvBIAok), [Info Page](../../balances/entropy/TheCarnotCycleVideoInfoWebPage.qmd), [Visuals](../../balances/entropy/116-Visuals.qmd)

### Two videos forward

**Sadi Carnot and the Power of Fire, the 1824 Edition Part 2**  
*The Steam Carnot Cycle*  
[Video](https://youtu.be/Qc9W1KKpouU), [Info Page](../../balances/entropy/TheCarnotCycleVideoInfoWebPage.qmd), [Visuals](../../balances/entropy/116.5-Visuals.qmd)