---
title: "*Under Pressure* Reference Page"
author: "DOFPro group"
format: html
---
# Purpose of *Under Pressure*

After temperature, pressure is the most common measured and reported quantity in chemical processes. The concept of pressure is fundamental to modeling, designing, and monitoring chemical processes. The *Part 1* and *Part 2* videos explain most of the fundamental and background information that a practicing engineer will need regarding pressure. *Part 1* discusses what pressure or force per unit area is, how you use it, and some of the methods for measuring it. *Part 2* continues the discussion with atmospheric pressure, barometric pressure, gauge pressure, absolute pressure and vacuum pressure. For those who caught the reference in the title, here is a [link to the video](https://youtu.be/ZyT8mVwf_40?si=8tDqHN07-LdtAHOn).

## *Part 1 The Full Story* Video

*The Full Story* Video examines common conceptions and misconceptions about pressure before explaining the basics of pressure, hydrostatic pressure, the different units used in measuring pressure and how to use pressure in calculations. It is recommended for those who have not been exposed to pressure before or who have struggled with understanding what pressure is or how it is used.


**Video Link Goes Here**
[Images](PressurePt1TFSVisuals.qmd), [Transcript]()

## The *Part 1 Just The Facts* Video

The *Just The Facts* Video explains the basics of pressure, hydrostatic pressure, the different units used in measuring pressure and how to use pressure in calculations. It is recommended for those who have a reasonably good understanding of pressure and are just looking for a refresher or a review.

<iframe width="560" height="315" src="https://www.youtube.com/embed/eZFMP-Dt48g?si=iSVAd8qT2tbC0wm7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Images](PressurePt1JTFVisuals.qmd), [Transcript]()

## *Part 2 The Full Story* Video

*The Full Story* Video examines common conceptions and misconceptions about atmospheric pressure, barometric pressure, gauge pressure, absolute pressure and vacuum pressure before explaining what these different pressures are and how to use them. It is recommended for those who have not been exposed to these pressure concepts before or who have struggled with understanding the differences among them or how they are used.

**Video Link Goes Here**
[Images](PressurePt2TFSVisuals.qmd), [Transcript]()

## The *Part 2 Just The Facts* Video

The *Just The Facts* Video explains the basics of pressure, hydrostatic pressure, the different units used in measuring pressure and how to use pressure in calculations. It is recommended for those who have a reasonably good understanding of pressure and are just looking for a refresher or a review.

<iframe width="560" height="315" src="https://www.youtube.com/embed/z8DJ4kpvCMU?si=Zo2R5czd2vIvacBL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
[Images](PressurePt2JTFVisuals.qmd), [Transcript]()

# Definitions

Pressure
: Normal force per unit area. The SI unit is the Pascal (Pa), which is defined as 1 Newton per square meter ($1\ \mathrm{N/m^2}$).

Pascal
: The SI unit of pressure, defined as $1\ \mathrm{N/m^2}$.

Torr or mmHg
: A Torr or mmHg is the hydrostatic pressure generated by a column of mercury 1 mm high. The Torr and mmHg differ by less than one part in 7 million so they are usually treated as equivalent. $1\ \mathrm{Torr}= 133.3224\ \mathrm{Pa}$.

Inch of Mercury
: An inch of mercury ($\mathrm{inchHg}) is the hydrostatic pressure generated by a column of mercury 1 inch high. $1\ \mathrm{inHg}= 3386.389\ \mathrm{Pa}$.

Atmosphere or Standard Atmosphere
: The atmosphere or standard atmosphere ($\mathrm{atm}$) is defined as the average atmospheric pressure at sea level. $1\ \mathrm{atm}= 101,325\ \mathrm{Pa}$.

Standard Atmospheric Model
: An agreed-upon model of how atmospheric properties vary with altitude on average. The two prinicipal ones are the [International Standard Atmosphere](https://en.wikipedia.org/wiki/International_Standard_Atmosphere) and the [U.S. Standard Atmosphere](https://en.wikipedia.org/wiki/U.S._Standard_Atmosphere).

Kilopascal
: The kilopascal ($\mathrm{kPa}$) is $1000\ \mathrm{Pa}$. $1\ \mathrm{kPa} = 1000\ \mathrm{Pa}$.

Bar
: The bar ($\mathrm{bar}$) is $10,00\ \mathrm{Pa}$. $1\ \mathrm{bar} = 10^5\ \mathrm{Pa}$.

Pound per Square Inch
: The pound per square inch ($\mathrm{psi}$) is one pound of normal force per square inch of area. $1\ \mathrm{psi}= 6894.757\ \mathrm{Pa}$.

Feet of Water
: A foot of water ($\mathrm{ftH_2O}) is the hydrostatic pressure generated by a column of water one foot high at $39.2\ ^\circ\mathrm{F}$. $1\ \mathrm{ftH_2O}= 2989.98\ \mathrm{Pa}$.

Inch of Water
: An inch of water ($\mathrm{inH_2O}) is the hydrostatic pressure generated by a column of water one inch high at $39.2\ ^\circ\mathrm{F}$. $1\ \mathrm{inH_2O}= 249.082\ \mathrm{Pa}$.

Meter of Water
: A meter of water ($\mathrm{mH_2O}) is the hydrostatic pressure generated by a column of water one meter high at $4\ ^\circ\mathrm{C}$. $1\ \mathrm{ftH_2O}= 9806.38\ \mathrm{Pa}$.

[Hydrostatic Pressure](https://en.wikipedia.org/wiki/Hydrostatics#Hydrostatic_pressure)
: The change in pressure from the top of a column of fluid to the bottom of the column of fluid, calculated as $\Delta P=\rho g h$ for a constant-density fluid.

Atmospheric Pressure
: The local pressure caused by the column of air above a given location. Since air is compressible, the pressure calculation does not use a simple formula.

Absolute Pressure
: The pressure measured relative to a perfect vacuum. Since a perfect vacuum does not exist, even in interstellar space, it is the pressure relative to an extrapolated perfect vacuum.

Gauge Pressure
: The pressure measured relative to the local atmospheric pressure. A tire pressure gauge usually measure gauge pressure. $P_\mathrm{abs}=P_\mathrm{gauge}+P_\mathrm{atm}$. The ideal gas law *must* be calculated using *absolute*, not *gauge* pressure.

Barometric Pressure
: The local atmospheric pressure that would be measured at the bottom of a hole drilled vertically down to sea level.

Differential Pressure Gauge:
A gauge that measures the difference in pressure between its two inlets.

Absolute Pressure Gauge:
A gauge that measures the pressure at its inlet relative to a perfect vacuum.

Gram Mole or g-mol
: A gram mole is what chemists call a mole. See [What Is A Mole](WhatIsAMoleWebPage.qmd) for further explanation.

[Troposphere](https://en.wikipedia.org/wiki/Troposphere)
: The portion of Earth's atmosphere below roughly 8 miles or 13 km. 

# Additional Links

## Preceding Videos

As of this writing the two sets of videos preceding this set are:

1. *Dimensionless Numbers* [The Full Story](), [Just The Facts](), [Reference Page]()
2. *Measuring Temperature* [The Full Story](), [Just The Facts](), [Reference Page]()

## Following Videos

As of this writing the two sets of videos following this set are:

1. *What Is a Mole?* [The Full Story](), [Just The Facts](), [Reference Page]()
2. *Mass, Moles, and Mass and Mole Fractions* [The Full Story](), [Just The Facts](), [Reference Page]()

## Other Links

1. The Wikipedia discussion of [pressure](https://en.wikipedia.org/wiki/Pressure). Units are discussed under [Units](https://en.wikipedia.org/wiki/Pressure#Units).
2. Teh Wikipedia discussion of [pressure measurement](https://en.wikipedia.org/wiki/Pressure_measurement). It contains discussion of absolute, gauge and differential pressures, and [manometers](https://en.wikipedia.org/wiki/Pressure_measurement#Liquid_column_(manometer)).