---
title: "Process Data and Process Variables"
author: "DOFPro group"
format: html
---

# Why Process Data and Process Variables

Many engineers and chemical engineers in particular design, analyze, and create processes that transform inputs, such as chemical reagents, heat, and electricity, into outputs such a other chemical reagents. The design and analysis of processes requires a knowledge of the sorts of measurements or data that are made of the process, and the variables that are used to model the process. This section discusses many of the varibles, measurements, and data that are common to these processes, how they are defined, what they mean, and how they are used, presented, and analyzed. 

## Conversions

We begin with units, conversions, and dimensionless numbers. In spite of a desire to perform all calculations in SI unts, the practicing engineer needs to be comfortable working with both familiar and obscure units. This set of videos discusses many of the common techniques for working with diverse units. The topics in this section are:

### [Dimensional Equation Unit Conversions](DimensionalEquationsWebPage.qmd)

**Is Furlongs Per Fortnight a Thing?**<br/>*Unit Conversion*<br/>[Video](https://youtu.be/5EbL9MEro9E), [Info Page](DimensionalEquationsWebPage.qmd), [Visuals](DimensionalEquationsJTFVisuals.qmd).

Dimensional equations are frequently used to convert data, measurements, and variables from one set of units to another. They will not solve all of your unit conversion issues, but they will solve many of them. Google Calculator is usually the easiest way to implement dimensional equations, but by no means the only way. Dimensional equations are used when units are multiplicatively related to each other.

### [Temperature Conversions](ConvertingTemperatureWebPage.qmd)

**How Keen Is Your Rank? Just the Facts**<br/>*Temperature Conversion*<br/>[Video](https://youtu.be/XKwl41MvFcE), [Info Page](ConvertingTemperatureWebPage.qmd), [Visuals](ConvertingTemperatureJTFVisuals.qmd)

**How Keen Is Your Rank?, The Full Story**<br/>*Temperature Conversion*<br/>[Video](https://youtu.be/hEtrCnIicqQ), [Info Page](ConvertingTemperatureWebPage.qmd), [Visuals](ConvertingTemperatureTFSVisuals.qmd)

Converting temperatures and temperature intervals among $\mathrm{K}$, $^\circ\mathrm{C}$, $^\circ\mathrm{F}$, and $^\circ\mathrm{R}$ applies the principles discussed in the previous two video sets. Because temperature is such an important measurement, datum, or variable, these videos discuss precisely how to make these conversions.

**Is It Hot in Here, or Is It Just My Thermistor?**<br/>*Thermistors, Thermocouples, and other Temperature Sensors*<br/>[Video](https://youtu.be/TncEECvmw8Y), [Info Page](ConvertingTemperatureWebPage.qmd), [Visuals](32-MeasuringTemperatureVisuals.qmd)

The most commonly measured process variable is temperature. This set of videos discusses different temperature-measurement techniques. It is optional because at this level it is not necessary to know how to measure a temperature, but it is valuable for anyone who actually needs to measure a temperature or has to specify how a temperature measurement is to be made.

### [Converting Equations with Units](EquationConversionVideoInfoWebPage.qmd)

**The Most Annoying Equation Conversion**<br/>*Unit Conversion of Equations*<br/>[Video](https://youtu.be/6dyg-CgAm8s), [Info Page](EquationConversionVideoInfoWebPage.qmd), [Visuals](EquationConversionJTFVisuals.qmd)

When units have a more complex relationship than simply multiplicative, such as $^\circ\mathrm{C}$ and $^\circ\mathrm{F}$, the relationship is expressed in an equation with dimensions. In addition, there are at times equations, particularly empirical equations, where the varibles are in SI units, and you need an equivalent equation in American Engineering units. The procedure for deriving such equations with units is presented in this set of videos.

### [Dimensionless Numbers or Groups](DimensionlessNumbersVideoInfoWebPage.qmd)

**Where Does Sherwood Hide His Unit? Principles**<br/>*Dimensionless Numbers Principles*<br/>[Video](https://youtu.be/A348vNv5t9c), [Info Page](DimensionlessNumbersVideoInfoWebPage.qmd), [Visuals](DimNumPart1JTFVisuals.qmd)

**What the Schmidt? Examples**<br/>*Applications of Dimensionless Numbers*<br/>[Video](https://youtu.be/74SD0k_qBc8), [Info Page](DimensionlessNumbersVideoInfoWebPage.qmd), [Visuals](DimNumPart2JTFVisuals.qmd)

In the early days of engineering there were huge data sets that needed to be regressed and correlations found. The [Buckingham pi theorem](https://en.wikipedia.org/wiki/Buckingham_%CF%80_theorem) provided a way to reduce the dimensionality of these huge data sets and ease calculational complexity. In addition, normalizing ordinary and partial differential equations (which is basically making the variables dimensionless through choosing a scale) gives rise to dimensionless prarameters. The most well known of these is the Reynolds number, but there are scores of others. This set of videos discusses dimensionless parameters and dimensionless numbers, where they come from, and how they are used.

## [Pressure](PressureWebPage.qmd)

The second most commonly measured process variable is pressure.

**Under Pressure Part 1, Just the Facts**<br/>*Pressure Basics*<br/>[Video](https://youtu.be/9gbOE5zEt4o), [Info Page](PressureWebPage.qmd), [Visuals](PressurePt1JTFVisuals.qmd)

**Under Pressure Part 1, The Full Story**<br/>*Pressure Basics*<br/>[Video](https://youtu.be/D-UAHVi4a2U), [Info Page](PressureWebPage.qmd), [Visuals](PressurePt1TFSVisuals.qmd)

***Part 1*** discusses the common pressure units and hydrostatic pressure.

**Under Pressure Part 2, Just the Facts**<br/>*Abs., Atm., Gauge, Barometric Pressure*<br/>[Video](https://youtu.be/CR3MomWlqb8), [Info Page](PressureWebPage.qmd), [Visuals](PressurePt2JTFVisuals.qmd)

**Under Pressure Part 2, The Full Story**<br/>*Abs., Atm., Gauge, Barometric Pressure*<br/>[Video](https://youtu.be/41axc-xnqsQ), [Info Page](PressureWebPage.qmd), [Visuals](PressurePt2TFSVisuals.qmd)

***Part 2*** discusses absolute, atmospheric, barometric, gauge, and vacuum pressure.


## [Mass, Moles, and Mass and Mole Fractions](WhatIsAMoleWebPage.qmd)

When purchasing, ordering, selling, or processing raw materials and chemical reagents, one has to specify the mass or weight of solids, the mass, weight, or volume of liquids, and the mass or pressure and volume of gases. However, when calculating the amount needed for a given chemical reaction, the number of moles needed needs to be calculated. The practicing engineer needs to be able to convert back and forth between mass and moles. The two video sets in this series are:

**What is a Mole? Just the Facts**<br/>*What a mole is*<br/>[Video](https://youtu.be/wbEkZmjNtwI), [Info Page](WhatIsAMoleWebPage.qmd), [Visuals](WhatIsAMoleJTFVisuals.qmd)

**What is a Mole? The Full Story**<br/>*What a mole is*<br/>[Video](https://youtu.be/CvRsRlpKll8), [Info Page](WhatIsAMoleWebPage.qmd), [Visuals](WhatIsAMoleVisuals.qmd)

**What the Frac?**<br/>*Mass, Moles, Mass Fractions, Mole Fractions*<br/>[Video](https://youtu.be/qJERzRm7xc0), [Info Page](WhatIsAMoleWebPage.qmd), [Visuals](MassMolesJTFVisuals.qmd)

 When dealing with mixtures, there are times that one needs to calcuate what mass fraction of each species is present and times to calculate the mole fraction of each species. This video explains how to calculate mass and mole fractions, how to convert between the two, and how to calculate mass- and mole-averaged molecular weight.

## [Volume, Density, and Flow Rates](DensityVolumeFlowVideoInfoWebPage.qmd)

**Are You Dense? Crank Up the Volume and Go With the Flow! Just the Facts**<br/>*Mass, Moles, Density, Volume, and Flow Rates*<br/>[Video](https://youtu.be/AFZWZSJ96g8), [Info Page](DensityVolumeFlowVideoInfoWebPage.qmd), [Visuals](VolumeDensityFlowRateJTFVisuals.qmd)

**Are You Dense? Crank Up the Volume and Go With the Flow!, The Full Story**<br/>*Mass, Moles, Density, Volume, and Flow Rates*<br/>[Video](https://youtu.be/2-EWSUW4BJU), [Info Page](DensityVolumeFlowVideoInfoWebPage.qmd), [Visuals](VolumeDensityFlowRateTFSVisuals.qmd)

In Chemical and Thermal Processes, the flows are often calculated and/or measured as mass flow rates, molar flow rates and/or volumetric flow rates. The video explains how the three flow rates are defined, and how to convert among them. The video is
