---
title: "What Is A Mole? </br>
       The Full Story"
author: "DOFPro Team"
format: 
  revealjs:
    incremental: true
    theme: [serif, ../../gradient.scss]
---

## Definition

- The mass equivalent of the molar mass of a molecule

- The molar mass of $\mathrm{CO_2}$ is $44.010\ \frac{\mathrm{g}}{\mathrm{mol}}$ or $44.010\ \frac{\mathrm{lb_m}}{\text{lb-mol}}$, etc.
- 15 mass units on N.I.S.T website 
- Most common moles are
  - $\text{g-mol}$ or $\text{mol}$
  - $\text{kg-mol}$ or $\text{kmol}$
  - $\text{tonne-mol}$
  - $\text{lb-mol}$
  - $\text{ton-mol}$


## Using a Mole

- Start with a balanced chemical equation.
- $$\mathrm{C} + \mathrm{O_2} \rightarrow \mathrm{CO_2}$$
- To make $100\ \mathrm{lb_m}$ of $\mathrm{CO_2}$
  - $100\ \mathrm{lb_m\ CO_2} / 44.010\ \frac{\mathrm{lb_m\ CO_2}}{\text{lb-mol}} = 2.272\ \text{lb-mol}$ of $\mathrm{CO_2}$
  - Need $2.272\ \text{lb-mol}$ of $\mathrm{C}$ and $2.272\ \text{lb-mol}$ of $\mathrm{O_2}$.
  - $2.272\ \text{lb-mol C} \cdot 12.011\ \frac{\mathrm{lb_m\ C}}{\text{lb-mol}} = 27.29  \mathrm{lb_m\ C}$
  - $2.272\ \text{lb-mol 0}_2 \cdot 31.999\ \frac{\mathrm{lb_m\ O}_2}{\text{lb-mol}} = 72.70  \mathrm{lb_m\ O}_2$

## Avogadro's Number

- $6.02214076 \times 10^{23}\ \frac{\mathrm{molecules}}{\mathrm{mol}}$ or  $6.02214076 \times 10^{23}\ \frac{\mathrm{molecules}}{\text{g-mol}}$
- $1.327 654 687 336 \times 10^{27}\ \frac{\mathrm{molecules}}{\text{lb-mol}}$

## Use the Correct Moles

- Unless the problem is in grams, don't use gram moles!
- Steps for using gram moles incorrectly.
  - Start with mass in units other than grams.
    1. Convert to grams.
    2. Convert to gram-moles.
    3. Use balanced chemical equation to solve for the other species in gram-moles.
    4. Convert the other species' gram-moles to grams.
    5. Convert the grams to the starting mass species.
  - Requires five steps.

## Use the Correct Moles

- Unless the problem is in grams, don't use gram moles!
- Steps for using moles.
  - Start with mass in units other than grams.
    1. Convert to  the mass unit's moles.
    2. Use balanced chemical equation to solve for the other species in the mass unit's moles.
    3. Convert the other species' moles to mass units.
- Requires three steps instead of five.
- 40% fewer places to make mistakes.

## The Summary

1. Different types of moles are for different types of mass units.
2. The molar mass is just the conversion factor between moles and mass. It has the same numerical value for all mass/mole pairs.
3. Use gram moles for problems in grams. Use pound-moles for problems in pounds, etc.